---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: pgbouncer-ro
spec:
  cluster:
    name: postgres16
  instances: 3
  type: ro
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "1000"
      default_pool_size: "100"
      server_idle_timeout: "300"
      server_login_retry: "5"
      query_wait_timeout: "5"
      application_name_add_host: "1"
