---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: postgres-pooler-rw
  labels:
    kustomize.toolkit.fluxcd.io/name: cloudnative-pg-cluster
    kustomize.toolkit.fluxcd.io/namespace: database
spec:
  cluster:
    name: postgres16
  instances: 2
  type: rw
  pgbouncer:
    poolMode: transaction
    parameters:
      max_client_conn: "1000"
      default_pool_size: "25"
      server_tls_sslmode: "require"
      server_tls_protocols: "tlsv1.3"
      client_tls_sslmode: "prefer"
      pool_mode: "transaction"
      log_connections: "0"
      log_disconnections: "0"
  template:
    metadata:
      labels:
        app: postgres-pooler
    spec:
      containers: []
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "500m"
          memory: "256Mi"
  monitoring:
    enablePodMonitor: true
