apiVersion: v1
kind: Secret
metadata:
    name: crowdsec-envoy-bouncer-secret
type: Opaque
stringData:
    ENVOY_BOUNCER_BOUNCER_APIKEY: ENC[AES256_GCM,data:F65L/OaYV+B/gxSwMCZiJYSYjRPU3xk/OYqrcX6r9/8LBiR0WKQ4malNug==,iv:sf4+0n50d0+yj2cjjGwNZzoMTnqEGFFvOVwH67enrUQ=,tag:BrjLHSu8+koe5QOYu77WyA==,type:str]
    ENVOY_BOUNCER_WAF_APIKEY: ENC[AES256_GCM,data:WwRHu6g8Tu9mqZRfjwmxGLN3sFEhmlfcW9IEx6ROMIvV6v8aP79yQogZ+g==,iv:vQkziYq8l1Jm4znR2oHnGTmiwTC2qZA05NFolXpoMJY=,tag:lALNRQKA+rh7X16dBskulw==,type:str]
sops:
    age:
        - recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyUitvNjhRWWw2eVJOZlc4
            MFF0RGJzR0paN0dPeEE4UGNlL1pKZW5kRlRnCjhTUDJvSGkxVTg5RmtZbDVyMlpm
            UUt5WFgraEJrc2w2ODQyWWk5MldiUW8KLS0tIHRVTjBmT0FPNHR1OXFhOU1wRm5o
            WGtvcENNcTl2TnFlVGRxK2FOdzhiQ3cKEyxGGflEY+WLkUMZwD2b+NQ1Tm4KoY+4
            ykw8+NEAPmL0bX3si3RkDGT+MVZr1Zh1epul5aRu1rQWbg/eTHXLFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T23:45:49Z"
    mac: ENC[AES256_GCM,data:zFouAGYHGLCY7P06QMfou4tsyZlJRPB68LLLs/yTEWTidz73qNo/ij1r2cR9LB3IUIMj6JhfhbhXUvutMdxb9J9GTFvdVTq9cxYyzkV9xOUKRjlzHOh44uJmrQH3cSXo+UJsmNyxTAgu/cY1gc9Pc0ZwJhnaKFsVDRVRMqPakvc=,iv:hdY457tlQq29zqj8MIhUZM/y8uNGawg0tKhzAKe5XoY=,tag:HrM6amdRDNv2j5CmtBnUTg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
