apiVersion: v1
kind: Secret
metadata:
    name: crowdsec-envoy-bouncer-secret
type: Opaque
stringData:
    ENVOY_BOUNCER_BOUNCER_APIKEY: ENC[AES256_GCM,data:dPdlsvH3S7o=,iv:+glsLpABMyorU7fNbFmulVRVKaiZO1ijBQDe7Z0YORs=,tag:A78zL5IYjj2LEj4eyIYK4A==,type:str]
    ENVOY_BOUNCER_WAF_APIKEY: ENC[AES256_GCM,data:tN41XH7Wads=,iv:QCW99NP+gjMpPCj2HLdsMs+9BzOGib2P0oW1pInMAb0=,tag:1i3FAp72vANJs3h52kvvnw==,type:str]
sops:
    age:
        - recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyUitvNjhRWWw2eVJOZlc4
            MFF0RGJzR0paN0dPeEE4UGNlL1pKZW5kRlRnCjhTUDJvSGkxVTg5RmtZbDVyMlpm
            UUt5WFgraEJrc2w2ODQyWWk5MldiUW8KLS0tIHRVTjBmT0FPNHR1OXFhOU1wRm5o
            WGtvcENNcTl2TnFlVGRxK2FOdzhiQ3cKEyxGGflEY+WLkUMZwD2b+NQ1Tm4KoY+4
            ykw8+NEAPmL0bX3si3RkDGT+MVZr1Zh1epul5aRu1rQWbg/eTHXLFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T21:04:20Z"
    mac: ENC[AES256_GCM,data:+iMuTqJL3JjLpsKdFn86POgDbcfecIu/XV2Wz1i1JtUxgTSA9YrrWVLJj5VcbrV3YoY14aBNG4z/orIlmGMVEz8etZ9Z5495YcDpwnC8VdLJsX5gd11NxemYRyppq0LxjJpNStD5xtGVx34LNlOAtLIxZhuS+shW0JqBlvieM0A=,iv:68kmoYUS8faP4W53CXhRKzgiHUDn9fTom6XP1rVv0eg=,tag:R0oKUtki0PtQBKwlIoRGuw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
