apiVersion: v1
kind: Secret
metadata:
    name: crowdsec-secret
type: Opaque
stringData:
    CROWDSEC_LAPI_SECRET: ENC[AES256_GCM,data:70mKl2m7EjI=,iv:rAohj/ZJO9F7wDyFTREvTQUpTZNWYvZ+9lCSGQH9bn8=,tag:tCAy367Eh00t6M3JDY6/0w==,type:str]
    DB_HOST: ENC[AES256_GCM,data:j68hX5KwVw7W0qnOgriqST3CK11veo1OcjMpXHCp8Va5SvU0g0iezA==,iv:Q1hAcZfBauE4cVVSpW/EAvnxNdwrxv7XbP45eDUSuD0=,tag:IS3w52KLv68qNlcD5SM0Vg==,type:str]
    DB_NAME: ENC[AES256_GCM,data:5LfKrxipeBo=,iv:G52WKrJ4zP//fwT0QdxrtQsQAYuSKtqZ5LAC10SHbko=,tag:qEcmriLVbIxFZIFeZu05wg==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:brHp81V5DmU=,iv:llLG3LxrU09JKdmoTFqAsZML6ARTYTKGSciOFWbrd3w=,tag:++CeWJcVRmpluq+eH9xhOQ==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:wjsVLqvXv7s=,iv:w2dYwJbTc++TCgDgKp4BWoXpZxN2w54u0uuI2JwEm0U=,tag:/ZhZUH1+oRdjKRR9ujV6rg==,type:str]
    ENROLL_KEY: ENC[AES256_GCM,data:/YFpBlcGaYS6+NusQm1P3X0SfvvLkBOcYg==,iv:DIs7LojdehrDcHY5m7DMi+vY/tUwCfvvGmdV1B16qQo=,tag:W2ALBKhU21S3d9cqmcR3qg==,type:str]
    REGISTRATION_TOKEN: ENC[AES256_GCM,data:5bTsLRWlMbB4AJZUZtQzMyi9dFcRCdfewA==,iv:oVZGmGwGViOLe0I5MQvH7RwooyLhsAcOxGMnQRIJojo=,tag:p8SceYxgoQXYnkIaMst08g==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:LwX87KH1PQ4=,iv:h7T2lXKA/Wvhvsxxpc62NS4GKVHRJ9ya/4FbJhjJKGU=,tag:99H7Bf4B1ik4ceJecrHvnw==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:SDMMKLtWAGB3kE5SKFsuSwHCE6xVT2u9vDvZ1ThmGM68Dao1QSLmrg==,iv:SGUC9E8CMS7FCBkVL36y9arGUc4O6GMzsof6jbTyzdc=,tag:GpDdPpUlhFD8pMuRhmA/IA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:ZzPbK9B0dog=,iv:BXiE21vlqv2T1KRFHKZvrxTq86rN638wAvMPMadamO0=,tag:BMtOxcoH98T28SN8fZA93Q==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:dczgoq/WYHc=,iv:0CZ7kGkYSVdls0YS7s2uN/JI/yOVjjJ8n3EO7jeRuqg=,tag:s9SL25XjMZ3g0n2bKMXRXQ==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:iTFxPIa4Gh0=,iv:pGYI0BH/7gGDr0cOO318nG8BQOFqKOBplb1dnFWNV1c=,tag:aFQW7uCnVCtfZw0GYUYRWw==,type:str]
sops:
    age:
        - recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ZlBSNVVSMFJXZG5wNXFH
            Zi82YUdod2hJektDaUw3MlVrVjlsaDM1MkNFCjlRTjZNSHFDb3pJSUhWZTRNRHU3
            MHBCdmNJYnVZakJzSlVocDdRS1ZEWkkKLS0tIHZqaWp0NGU3NnhqVlREWjY5L09Z
            MkFESG5DSmIyK0RBcTArT0VPYnlNamcKKbki53ao3rSxFuqgaiv227gj+j/O0Td9
            XsMT0vre6B0GdzVd0BFWGy1QNunDFaJ9QZigf+p7X+zjswmjKOIKzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T21:03:27Z"
    mac: ENC[AES256_GCM,data:S18feu645bG0Ltsaxz5VlZfDQR+sYog2QgQnqULzxIol+P7c9/G826Gx/LxSlgdjpKtOQS6XJ3VvTwuZXymI6fKZq2CswuBDXmKZ9Uf69HwMFL7fF2pKQuwDMrfpx1DRmFEU+zy1O5vN447ZuZuSmO5jWS5Etxs0yp0etsawCf0=,iv:wOBVuxSSNCUntejTGRI64aEIGbV4+JQDbwj6cUM/+ug=,tag:XoYs09n0WU/d9HCaLvb9Gw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
