apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:H736mPIyKfxmBwUElvLFK4tWWcOhI/TX+eQb+uVDO0/ncORRaXenB8W6BN1YIO4nxkoIP1znq0h8njKPPdKrnCYuCs8b7J1ITD2m8atDNC9zxK2ZMZ2CWOgUug7j3H86lUek5Solu0gsxAbwVO5BMCWQ8y28UEk+/w==,iv:GxVfN5+5/sVstGJYcvTsH/pensXX1aB2XgNNmKM1EoA=,tag:s4HFVnV4ml/pgtvkRP0hgQ==,type:str]
sops:
    age:
        - recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQ1JteGFHYzhUZFJHWUNm
            M3ZGSzJTSy9wMnFaMWFBNzdaZWxWc1lJbndBCjdpWm1FTytINUx4QTVoTHdvNVN0
            dWNUeEN4TVYyM2plczZFQlhHc25qSTAKLS0tIFdZaVJjdGF6RGk2SHFQaVI0dVhx
            cTB4aldLS2Y1eS9lSkZEQ2lrcThvQWMK91aAyuC3Vn6I/p/nduSnlvOK45+G15YV
            JfDzO2Fhvb6cEwQsECPcxnmCuoN1BSaMmGFLrsRu5H2eu7SrJ2ptSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-20T12:55:40Z"
    mac: ENC[AES256_GCM,data:5cnk3elUqx9X4s1NFRSvzjC8peKoWuQK+5xHeOUDuIVZs71ChSEVlu6yAq3WbMjgDVTL5KR3+Y9/TTgzfySKIssQD9/J4MecFo+AGaKUjFPgJ5hKcKMa56ULB5NxEcj9H5Os+mCgY/uCc1GDMQ23qHyE/iBa+w9iGDtpG+mdga8=,iv:X4vWXSaCGCyeP2Ux3F8GYt7YBAFNTlvZTQLw7cP1FrE=,tag:YD2xcs7syCL2KtEsRM8uTQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: homeassistant-prometheus-token
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:/cS+v2M4xI5owaem8ANTCyr3VFD4MsdPzTXj8YSmBsZeKgsRdizHqFSsnOcoeYTUNRwdjimDDcNjiRp/9MlIkie/hre8YXsviGp0XH5vmdSxP6uhsML4vdyI3hSDTn7qVrvgMv2OtsTDTEdClnqnO5lO8lYDrGkLcANM0owGarh6ST6P0BDpzH6nTmCi6oqV4GIPuIW8UC7i8HNU0hbcHQSmsFki4pIS6GkMg8QsRxhXVYf3RZ84,iv:ClCQlO1j4jblWKjTgaXgeRBZ8R5WZ4QCPGr8+6uw9Vw=,tag:orG0n3fEQFbL31cT7l8QpA==,type:str]
sops:
    age:
        - recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQ1JteGFHYzhUZFJHWUNm
            M3ZGSzJTSy9wMnFaMWFBNzdaZWxWc1lJbndBCjdpWm1FTytINUx4QTVoTHdvNVN0
            dWNUeEN4TVYyM2plczZFQlhHc25qSTAKLS0tIFdZaVJjdGF6RGk2SHFQaVI0dVhx
            cTB4aldLS2Y1eS9lSkZEQ2lrcThvQWMK91aAyuC3Vn6I/p/nduSnlvOK45+G15YV
            JfDzO2Fhvb6cEwQsECPcxnmCuoN1BSaMmGFLrsRu5H2eu7SrJ2ptSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-20T12:55:40Z"
    mac: ENC[AES256_GCM,data:5cnk3elUqx9X4s1NFRSvzjC8peKoWuQK+5xHeOUDuIVZs71ChSEVlu6yAq3WbMjgDVTL5KR3+Y9/TTgzfySKIssQD9/J4MecFo+AGaKUjFPgJ5hKcKMa56ULB5NxEcj9H5Os+mCgY/uCc1GDMQ23qHyE/iBa+w9iGDtpG+mdga8=,iv:X4vWXSaCGCyeP2Ux3F8GYt7YBAFNTlvZTQLw7cP1FrE=,tag:YD2xcs7syCL2KtEsRM8uTQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
