apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-exporter-secret
  namespace: observability
type: Opaque
stringData:
  NEXTCLOUD_AUTH_TOKEN: ENC[AES256_GCM,data:fYrbOPf8sAfM8yC8aNFvB7/dfFPMfblfnZ1QH4SNKaDmjBtXU0lU5e6V9e2Sdke0mPE7iLYhoYuXnEJQCBWxqA==,iv:bQbroZGfFgvfQj5peNNc3GFS2t08ZmOZgOLCgnP6gHI=,tag:TQZcos5gyynv9zhvDtBe4g==,type:str]
sops:
  age:
    - recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQakJpYkZCcU1YVzVTMFhX
        RC83ek1rY1VpMWRUSTU4OXlLQnZjbVBiOGprCkk1cGVrRUdWaTVQeVkxWTBVazFp
        b2VMcWduekUwWEUwZ1RjTkVXbkc5SlUKLS0tIG5DUUUwYWxyOWNUT1NIM1I0VkM3
        bHE1U1N5ajk0UUFCMk9jVWwzVkxvdWcKVqkpmi1BMHNIXFar8YhWWgoOPqCZehwG
        zJz4S/gdAH65Xy3u2Njxr1sH2dToYsAP41jnTp2y1zjzpxes/VZ5zw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-02T11:23:48Z"
  mac: ENC[AES256_GCM,data:G9bIXnU2yh2cvKqEWYmz/42i3/OZ5fNuckd1mljeSdSkeq3gSF5VokZq44NiY4bjObHLXWwT45/ScRhLv/NyMA4XUYW7071ivQhId82WmfFnD1g8GqO/hflt9PsWvOApK5dnkK6mC8Nlxku6ZyigHYRqbXEFALuhGLmjFqHCu/U=,iv:CXpraCsLU6o6Nc8Cy1c4jqrlwUNLMlr03xXeoXLvMiw=,tag:9FDXSxX6UfVDiX5MoFk2EA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
