apiVersion: v1
kind: Secret
metadata:
    name: picoshare-secret
stringData:
    PS_SHARED_SECRET: ENC[AES256_GCM,data:yCgeRgif2jnHAGfKFytr,iv:TcKov2teUS8zQkSRfaUE9WRJkrwyVIogueAIS024Qak=,tag:0Ixv98DdWLw4SeAdrTPciw==,type:str]
sops:
    age:
        - recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlTzBGdlFydDNoZ2o5QlR1
            Y2N4eGhYT3ZQQmo4ZnVTSDlZbTRNOU9tdm1rCll0YVpBaXVsVThHc1ZENWkwbnBN
            OEZLOExIS05qcm0yRzc4UER1OFBSaTgKLS0tIDhMSzU4ci8rNldqdjRBVUdSd0c5
            bVY0ZjdKUlhXUTlsVUlaTks2S0FYUW8KVpTp2aFV8VcIs4UV6rD8wxngoawV6kk2
            Ax2W2FVikNQzYxgM5gVnM22xGnC50Cx1kSEZoI6DPF1RC3r8fW6wPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T01:25:40Z"
    mac: ENC[AES256_GCM,data:Jm4g3WazHNsBQkJ0cgJkOwGRefmPIWbn0U00jWwXMC5TH+E2cD0oKJqCEPU1CQ3Uc8QvxOSYWzPyJe9Yud0D+Dl3ojHhjCjP0KEOP/8lJMhshJJeGXEjNGKVYRLTbEAewqzIiuhSr0iMd05PO0QB8YHAJYXdvO7M2MWqRnPQuSo=,iv:1jMMjubp1B/gHNndUQgxLvKRoTlVlZnk1KbkGn7pAhY=,tag:f9eomFFdWQleyHGdCuQc/w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
