---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netdata
spec:
  interval: 30m
  releaseName: netdata
  chart:
    spec:
      # renovate: registryUrl=https://netdata.github.io/helmchart/
      chart: netdata
      version: 3.7.157
      sourceRef:
        kind: HelmRepository
        name: netdata

  valuesFrom:
    - kind: Secret
      name: &secret netdata-secret
      valuesKey: CLAIM_TOKEN
      targetPath: parent.claiming.token
    - kind: Secret
      name: *secret
      valuesKey: CLAIM_ROOMS
      targetPath: parent.claiming.rooms

  values:
    image:
      repository: ghcr.io/netdata/netdata
      tag: "v2.8.4@sha256:7da6bcb5809aee11f4830b9a000a6d6bafb43b05d7b6103dfd1a9438d61f5765"

    ingress:
      enabled: false

    parent:
      enabled: true
      claiming:
        enabled: true
      alarms:
        storageclass: "ceph-block"
      database:
        storageclass: "ceph-block"
      securityContext:
        fsGroup: 201

    child:
      enabled: false

    k8sState:
      enabled: true
      persistence:
        enabled: false
      claiming:
        enabled: false
