apiVersion: v1
kind: Secret
metadata:
  name: netdata-secret
type: Opaque
stringData:
  CLAIM_TOKEN: ENC[AES256_GCM,data:polVjXOqKOwbFYwi/G+VkH2S81i4dRlYpUBWFcsHx3OIAJ5eyBa++Ctaswxf6k0lJBpGS7I5sGJfyNi9cvsAPuJbxTV/WmCTnrgYdygFLE9gx1JhkdxhJaIu6A5pVadjISCYf+cAlDuSz8kfA+YqkCEdvpRyJF310kjvXK5DivAQGpT51jVm,iv:X+6cOzAmFCF6JiFFXgsx7NMGGUZ5rgmBRX1Tj4WvLZs=,tag:rl/sgGUS0blx6GGj2YqwRw==,type:str]
  CLAIM_ROOMS: ENC[AES256_GCM,data:8qL7lzOieLelCyOeN/uMXfKgx2zd7H9Ngo/eBw6MMKQlQbpo,iv:DF3KwhzYJ//JIxlH3RyicWMehrEirF6tKn8LO3EoQPE=,tag:en0pCP2GXqMrznD5DDcrtw==,type:str]
sops:
  age:
    - recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBycmdxUHoyOWVpMndvNExo
        RElERE5uUEtndmNXcmpOYUZPdlF4Q3lkR0FNCmRZb2Y0N2dFRlBWemFlZ3MzUVVS
        M0hQcDQwNmJuS2tyMGdsMEo0M0tFT2MKLS0tIFhiWGNob0VSalZEb1cza0pXcWcx
        ck1uSzJGUnVDb216ZGFJSjJxS3hXemMKrmdsEKW3Xarmgdb5U9QxMd4XjrArkFAU
        Yi3shTDMaLQQiQExesMHe9SDUMF5cja5qDa2+yy3ShbKddpR++rVeA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-21T20:33:44Z"
  mac: ENC[AES256_GCM,data:o3dMcyebJFeSfPtPb39dw4vz0BLTzr9bD/RnW1/RC35fToxeNzB5BEIRThE4ezyMNyM4nN8Fv/sy63cWqC4hL63oBhZcT/SMYqGc4hyGnfnVGabVZS29BhHC5SsZv3+ZuRAPkafbCvbl9LP5HyOn13Az/YQnXf6M3LDvtWt/2T4=,iv:q/SZqoeBLFsgHCwBM3uzCw6rcPkKoUK03vEgpNLSVxY=,tag:saghmzu0xCw+La3ZMhV5GA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
