---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: netdata
  namespace: &namespace observability
spec:
  targetNamespace: *namespace
  path: ./kubernetes/apps/observability/netdata/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 30m
  patches:
    - patch: |-
        apiVersion: v1
        kind: PersistentVolumeClaim
        metadata:
          name: netdata-k8s-state-varlib
        spec:
          storageClassName: openebs-hostpath
      target:
        kind: PersistentVolumeClaim
        name: netdata-k8s-state-varlib
