---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafanadashboard.yaml
  - helmrelease.yaml
  - secret.sops.yaml
  - nfs-pvc.yaml
  - ocirepository.yaml
configMapGenerator:
  - name: nextcloud-scripts
    files:
      - scripts/cron.sh
      - scripts/post-start.sh
generatorOptions:
  disableNameSuffixHash: true
