apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secret
    namespace: default
stringData:
    NEXTCLOUD_USERNAME: ENC[AES256_GCM,data:wYeTpnGSQEG/smACH7JAkMN9fkA=,iv:G2SbHwnM9dG43Wc3rjFoA4orPrgMg7VcPfXQPNS2CW4=,tag:ZrKd9fLvEsMJY3hp+tF8KA==,type:str]
    NEXTCLOUD_PASSWORD: ENC[AES256_GCM,data:jiV/ySPm3GBShCgnpsNh,iv:niQ5RI50Tm/8w3yGs1znDd4I6tGFreABob44MQg3u7E=,tag:owhtlgy6wBS3wH9eIqN5kw==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:fwU5E/rPk/olYmGV7Rv9sea/CJ0K3rCixHlGSyc=,iv:wnT9+/aiarWsFip4RH7Ew3IAODLwlxJLqJkmfEcYDdo=,tag:ltnko5QVQp49cmmo0NUAcQ==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:R5+XHpgBkb4=,iv:W9R8/xHQrvEnfOntfRdpW9Rmwrd7L6ePHTyca3Gi7j8=,tag:rPYeoCs9dlHMsDDjL2mh9g==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:pQRFpleBDIGcmWDJcqo=,iv:AcucEk3HZPhDy8P2A0hh9ZAiXSs/QizjUy+kMIszNLU=,tag:90/AEiBFAEds3/3HTnkh7Q==,type:str]
    FROM_ADDRESS: ENC[AES256_GCM,data:IbnpRogDqNaa9SO4FZe7D/FQCQ==,iv:BCo1YhdDEdzq2/I7QOv+SpxXHmIJ9fNGb/JsrhFkK7w=,tag:+diMpCJRbPuEbx6hzPkYhQ==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:SkMlfoJvruoM,iv:h3ru6PPcCrqbLa/B20+gxLBcUzWSS/03Ga7DdOd1Nd8=,tag:arAIWPDjBh2yPZ0Sc22VzQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:gNHkvfBrRaczNCt8LQmoCgtxp3+EV5WlHKt3mfJhm0uihbSLyxw59A==,iv:LrLPfBd/HZtydVIqFsu89fgnJrAzB0adghZ+SGASOyM=,tag:TXewSHUWkQA9aGAHJk8P2g==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:Tfj44gXzF24W,iv:HSSqrUuTo6HPhMOYR4NZ30yFhuOx8CVrFizJrYTVB3w=,tag:wcddSf/JaJzndPjL8GD+1Q==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:LGbrhnlYil8=,iv:DjDlqOaCuN78xDS/PfKCF62A2+il2oHLnHKpFc/koBI=,tag:HI175tfBJqFaP1znQQKOWQ==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:mNPjy5NvHxg=,iv:EWI8qwDDYm+nHsyw6KJ573cF+Yy2OmYo8vLfS02TIxg=,tag:UEIJtJklHMAjHOR/Essz3g==,type:str]
    replica.config.php: ENC[AES256_GCM,data:zyiosK/PdkaALAx1JCq1SQlkrvJlCEF168cXrBjHDkBu8wNzR4eF9/JRkWY9REGT6QJliQyckKaLCzSfFFuEFyKK8qGeOJggZeBx0loFcNgmlKtPNMDZTqRVaYd2rHhIe9qyIecg3pcQ934+ppNcnD4q+fn2928VjbYwkGPbjtQCGHJTJvgonDAhDUnYFmz/Oz+FKektyq9SrY4RyXq8LZIIMaWlH+zK39bdh2zquvc9nidMTaTY6RnCWwKXAfQCehfTP8IPw4faJ9CVxMYMseYhCIKo8LPvQEwPVc7APUgo5s4J5dXCo3lG22u+pQiPf6PFdgDDenjClSg3Tk4I//h7AEuLfBQ+NvR/IOgMpdKJOmks6c9Infj0zCE/uYH3tZmbNg3gyxYJCCktI0H0PELlo1G8rDpozXX56g==,iv:ZHFXa6YJmIydenQfrMyH5ZsWO98cLpo6l99Lu9A6mrs=,tag:LBnsiUKoNC6KzskHB5KotQ==,type:str]
sops:
    age:
        - recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwWEVMYkFjNWRhU0hPSVNl
            WEVwTWxDQlE2MmVkanQvQ3Z6aUs4d1VyVUVjClhwRVRaZWJPcEs0am5ZSnVZSm9n
            NU80RjFuK3JHdmtPcCt5bHNIQnB5RDQKLS0tIDVCOEdXVWRWeGFiZU9QcThZeGtZ
            SzNEMGQvKzVsZVVNYTZZdWQvMnh1R2cKJ6MTlhKcLXJZt0UKx0iTQDpxQJBUNnoL
            chP9QhTdIDtqYBRsi8xsfkyvDtCsZSC4v5Qi1NklelcP7G/LPfv/sQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T20:15:43Z"
    mac: ENC[AES256_GCM,data:3DGxPangoMnR0ML+p5o32GgMwXDRdwgYkvoF0UzGVb/UQSZDnnn/WcqRrcTL9k35L+UQgKUMC88WMQHYxeCz2X5iNB9KMzADpwRn+Ky/3xQr5+Nrz+NWY2i7gFPDEVHvwzUfys/RWWFLZqJO38vA/5dUWDxvaoIzcwt1e8gSuMI=,iv:AsNpohATU87tSBhS4n458gwpZ0V1Jz1xUOgphc4NL4g=,tag:pQMwGm2qkrqy3hDX5c5g5Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
