---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: monerod
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 1h
  values:
    controllers:
      monerod:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/sethforprivacy/simple-monerod
              tag: latest
            args:
              - "--data-dir=/home/monero/.bitmonero"
              - "--log-file=/var/log/monero/monerod.log"
              - "--rpc-restricted-bind-ip=0.0.0.0"
              - "--rpc-restricted-bind-port=18089"
              - "--no-igd"
              - "--zmq-pub=tcp://0.0.0.0:18083"
              - "--enable-dns-blocklist"
              - "--prune-blockchain"
            ports:
              - name: p2p
                containerPort: 18080
              - name: rpc
                containerPort: 18089
              - name: zmq
                containerPort: 18083
            resources:
              requests:
                cpu: 1
                memory: 4Gi
              limits:
                memory: 8Gi
    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      monerod:
        type: ClusterIP
        ports:
          p2p:
            port: 18080
            targetPort: p2p
          rpc:
            port: 18089
            targetPort: rpc
          zmq:
            port: 18083
            targetPort: zmq
    persistence:
      data:
        type: persistentVolumeClaim
        storageClass: ceph-filesystem
        accessMode: ReadWriteMany
        size: 200Gi
        retain: true
        globalMounts:
          - path: /home/monero/.bitmonero
      logs:
        type: emptyDir
        globalMounts:
          - path: /var/log/monero
