---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: internal-opnsense
  labels:
    kubernetes.io/service-name: internal-opnsense
addressType: IPv4
endpoints:
  - addresses:
      - 192.168.0.1
ports:
  - port: 443
    name: https
    protocol: TCP
