---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: ${APP}
spec:
  sourcePVC: ${APP}
  trigger:
    schedule: 0 * * * *
  kopia:
    accessModes:
      - ${VOLSYNC_SNAP_ACCESSMODES:=ReadWriteOnce}
    cacheAccessModes:
      - ${VOLSYNC_CACHE_ACCESSMODES:=ReadWriteOnce}
    cacheCapacity: ${VOLSYNC_CAPACITY:=5Gi}
    cacheStorageClassName: ${VOLSYNC_CACHE_SNAPSHOTCLASS:=openebs-hostpath}
    compression: zstd-fastest
    copyMethod: Snapshot
    moverSecurityContext:
      runAsUser: ${VOLSYNC_PUID:=568}
      runAsGroup: ${VOLSYNC_PGID:=568}
      fsGroup: ${VOLSYNC_PGID:=568}
    parallelism: 2
    repository: ${APP}-volsync-secret
    retain:
      hourly: 24
      daily: 7
    storageClassName: ${VOLSYNC_STORAGECLASS:=openebs-zfs}
    volumeSnapshotClassName: ${VOLSYNC_SNAPSHOTCLASS:=openebs-zfs}
