apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-volsync-secret
type: Opaque
stringData:
    KOPIA_FS_PATH: ENC[AES256_GCM,data:8T3HVVJSOZgJxAc=,iv:0mZsWx1I/+FPvpuGkzvHuKjXsWvQxkjuti+6ZMjceUA=,tag:EZY02bG9pe2M2RqjrvkiqQ==,type:str]
    KOPIA_PASSWORD: ENC[AES256_GCM,data:SzHKmuAp3Xw=,iv:y5SfzkhN55iOAbnWhnC4fhOJLM0zKA5h6gJxcYcTYaI=,tag:UaIWcRdKPdC2tdC/hHuEiw==,type:str]
    KOPIA_REPOSITORY: ENC[AES256_GCM,data:BxLsXQt44niDkd3HZwiXBYb8HxyKar04,iv:n+IIpXeR94weOYZP3sOUwRIugi/Gs4jpmDjALIxsqhk=,tag:6hzq8B8HI3c8PgJHdzO73A==,type:str]
sops:
    age:
        - recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCcHRCemJiTHdyZWFxODVI
            b2ZpeEFINko4N2FOd3loQkNWS2VzVDNDTEE0CjlVOTlsaFlXS2N6VlVGMHdFS2pF
            a0dJbDRqalJGQm9QelJrQjI3eS9TYjAKLS0tIFd6RkFNejBrekJXQjAreTMzYUl6
            R0JCNTJybk9yQWt3SFo3NXg0cDZ1aFEKewD3K2im66SLFhVhUBbIj69dvrsWvphZ
            c9ZORmLdDON3Argdorql1MfEGIV7y4E9HF62VVeJvzgsv156kxxP1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-21T19:38:51Z"
    mac: ENC[AES256_GCM,data:tTaJOni6AU05Sf/cAFx4IFXBI0BL58f5rOgb4p7IrdovvgKEqG05F2yi4RJs/nk/ct3KzqoShghRPsxS7uTwkaAgMZ9ywzkhF9+nnLBg4MC1LYIj1OMVloYliE/IEd1aXUVNVz/r4teyCJQHtFoid1e0nH8g/VQ899S8rBMUHXI=,iv:0/0q5PAjTRZ60wrC1AdsWclaZ/IfTngzOdQBmerogd8=,tag:g5WQJIa95MzCZE/rD2FbcA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
