apiVersion: v1
kind: Secret
metadata:
    name: facerecognition-secret
    namespace: default
stringData:
    FACERECOGNITION_API_KEY: ENC[AES256_GCM,data:qpmLK4YPi7CdSvfrO1ng/Wbf/DMpdXjcYmeZz9Q5H2DBDXR8f+xXsNXTQwk=,iv:sUJYZw0iV5nPN/8bKlWQNjtY7KE83PTA/Q5Sq8fuM0M=,tag:9Zl+VKXAgLUET7D7DUnVgQ==,type:str]
sops:
    age:
        - recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFTWg5M1kzY0RQNlNwRlJ3
            Vm9HVzRKZ3dKc3BBYlNXdkZtcE5JenZyc0Q4ClM0VHRzcDBHSWxUaU40TjVWU1U3
            MFE0MXZNRjN4WjRXYVU3Q0hUc3drUEEKLS0tIHlPQzJkbzUyRHUyeWl1dGRRQ0d4
            TFR3elJLSTBjWEJVWHp1d3NRdmJXTjQK6pEzKd01xBhGG1vh/Fpvxw3sxdb1Nf96
            PrYNGsltvTDZOe0qQ+k/KvkQF+VMwj+sX5lxG2365flwWdHG1a2MYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-25T20:18:10Z"
    mac: ENC[AES256_GCM,data:Nme56VYPA/wAj1e1dOG0AM6KsYD8P+ue571Ftim+W+jQG4J4O6hbl99Sdpj1E/nwsKhlRS6JLSpU9f4xsDsO+gLxC8VSvty3sQ7qdvVPcCdIsq8gt3MBYXaLPvn1v1CZq4yKfubW7r68/jk84dnvxSH/NHsRDd6Thu0NFSD3AcU=,iv:V/GknOyER9PB4RJveIh/Xz/ZUhcko3Yh88xPDEV/sM4=,tag:LQuFJD59X5n+hKjEfqx/jg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
