apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
  namespace: default
stringData:
  FACERECOGNITION_API_KEY: ENC[AES256_GCM,data:qpmLK4YPi7CdSvfrO1ng/Wbf/DMpdXjcYmeZz9Q5H2DBDXR8f+xXsNXTQwk=,iv:sUJYZw0iV5nPN/8bKlWQNjtY7KE83PTA/Q5Sq8fuM0M=,tag:9Zl+VKXAgLUET7D7DUnVgQ==,type:str]
sops:
  age:
    - recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFTWg5M1kzY0RQNlNwRlJ3
        Vm9HVzRKZ3dKc3BBYlNXdkZtcE5JenZyc0Q4ClM0VHRzcDBHSWxUaU40TjVWU1U3
        MFE0MXZNRjN4WjRXYVU3Q0hUc3drUEEKLS0tIHlPQzJkbzUyRHUyeWl1dGRRQ0d4
        TFR3elJLSTBjWEJVWHp1d3NRdmJXTjQK6pEzKd01xBhGG1vh/Fpvxw3sxdb1Nf96
        PrYNGsltvTDZOe0qQ+k/KvkQF+VMwj+sX5lxG2365flwWdHG1a2MYQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T20:01:38Z"
  mac: ENC[AES256_GCM,data:HfmN3jJJGoinULDGq/SqZ4TsO3NfHVw5EpipkwLiPRxVD/CCYZK0bEdUrOFFA+mD8aNyfXxYQAnxy6p19Pwj30PSKB+XTN7nguRAI/5vRRQKxrX1vh5cBDybfKthPTK7wf2gn31i3c8wa30+1GLcnSB2whiCXWGgMM0KqA92Avw=,iv:Mt/AGn4ytm56syYevtb7dbY4R6e8buDuZWQ079ZAJG4=,tag:ApTWuWoWGKL1NzpFS+jdKw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
