apiVersion: v1
kind: Secret
metadata:
  name: streamystats-secret
  namespace: media
type: Opaque
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:UHB3Q9AsQi3RFUfOV0Xy3Fs6d0WSkiBCXChWmasibZHoA/mn3N3j2C6aEUhiVSXwcr/wcFwS17ozvycrVHAwgwJxfcheDG2ZuxPLn6rnqDBMwhMU0PHKrA0N7H3y,iv:fba1nxLt3YXB15V1dT2wxgI8ARq01s+ZbnCoLmpkwHw=,tag:wlTgFqb+LBGGZSdd2pi1KA==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:Fopz2MSSx1Vkq6xZ,iv:N59XhA2sxgL49LeJQQs1DvPZaDhmC0xGKBXc+uhxNwQ=,tag:/NahRDPBR92nb6HUSlmlgg==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:tsvxhpSKkqZeKuNxsgX/so96X0cPTWDqJgz4P6sn0+W9tfBfB8aSyA==,iv:NqAl1Et8z48J+DgODP6OAkuRww3EdlDeSygxidmw8Xo=,tag:4YPyJbHZNIlcahZApL58ng==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:KpEMs7d+8/qgaFP7,iv:Sz4hAtxNoHhvonm2uLFqYEGxgL1jiyg1b/CR6uflXdg=,tag:Dp3hvo0k/8dPGmubo8sNHg==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:7THJwnTrrec=,iv:p5onXZOWIruZAiuF7MK0KzXtdWMq1LSWE2O3okEZcz4=,tag:WIa75zlR337VXmBgIu8fqA==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:UR1MpMX44j8=,iv:ts8o98JA8+RA9sfDHSlReppzzYTagrdK82Ykd/OsqbI=,tag:ptlaZLg0layXXC4WKn7UEA==,type:str]
sops:
  age:
    - recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKTWFkUnZKaHhNOUpzb1BJ
        a3R4TUpsZDRrbTR0eDNGQmdDRXQ3bDZnbFdRCkZLRmNuUVhDSDIzSG90djhSVWQ5
        cjJyR3ZHcG9WanN4Skw4dUVJeGlJbmsKLS0tIHJyZTg1OVdqSHVaSzJLL3dYQWVX
        cXJETlJ2Si9CTFhKOVZscG52N0I2cm8K+AxX9+GQz3QAreS69wvQH5Lw743xrZvS
        A53gdIRwKNuTAk66i4otXEDcIIikDpktNfE3M1fAXqATh8gEr6AcAg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-25T14:09:13Z"
  mac: ENC[AES256_GCM,data:zio/HhOkjp+R3Hlwii/SBl8WydeogZxGQPgiOJCWSWKQxXrfdFAIsA112EQMFKSuCQYMQr5JZGFdl2R907bGw2jaaxpfK/nxCGZqV0VcSj4zBNXcaf3qp2AKvwpefK/tYb40wGbNYnYcV2kNFAwYKqAzPV5YGfCP2PHWdvF8Glo=,iv:1aquLwYjlUMWKE3K3WyFmdROFwPaJFaewcltCcFiBt4=,tag:fU8bG6EKSxbL5btFgrMGGg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
