---
apiVersion: v1
kind: Secret
metadata:
  name: karakeep-secret
stringData:
  encryption_key: ENC[AES256_GCM,data:cXtBaWKx0HAmlQ==,iv:Au1ge3es15/XVMt+bmpYAodydZKY0e1KCyxd29waDW4=,tag:ti3XMexAVomvIhzeslpmsg==,type:str]
  meilisearch_master_key: ENC[AES256_GCM,data:On2fmT3rDhbulQ==,iv:5azeCGxp9hSGxaks1ZN8Z0/IgVmhZMQxk4fpK1Tfzxw=,tag:hRuRuUIiP4SwDMWjfH7z9g==,type:str]
sops:
  age:
    - recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3bDRPWEl4dExuV2NRckZ6
        Nkh2WGRmVUNvMzFUWE9IOEdndzNDSUgva0NZCk1PRWZtL2NYOGZXMW5VNHNIRnlR
        cy9qcmNPdEt1Tk5XNkp0WmN5UDlEeHcKLS0tIFNRRXVkMFhYUXZBSmVsdmdwT2tz
        OFlWMEc0RDg1Y2Y1ODFReXlWbGtjaW8KMltI70a2ZKNRD1RHT3TNTNMPogYcHoWt
        9M1OyOBCPkVt70QZEPDrDJy+kJgyP3FliNVRI0B+SG6CCqUGKbHoMQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-21T14:17:41Z"
  mac: ENC[AES256_GCM,data:CEqsZIj8HxaOU8PcOizRreIjGg1F/mtocErG7axC/tKYzUdx0buvc+f+Kee5x460xkYvX4vK9Lk3Cw+MOrMBw0RQIWETNtxrmZEVrcSJpAMmHUObFykenTN6YEeKVNGHQymsVJrcxF85SrdUbfVh6n245TcjHQ29EYqDEP+LrbY=,iv:wP55jjQVs2uP13ne7lV1jAS4PnSg2h02kEgTxL+nn+k=,tag:us3Jw5IvLhWWG28n53XemQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
