---
apiVersion: v1
kind: Secret
metadata:
  name: karakeep
  namespace: default
stringData:
  encryption_key: ENC[AES256_GCM,data:Iz/BEP1lovpM+pRQCuY/sh0CnZvT/6VFA4U=,iv:zxmxY4mRVscf5UH9BhLDLCWHFZQrNamIBndzly47oH4=,tag:Q2DAFjGeY8T9dy7DVOCWHQ==,type:str]
  meilisearch_master_key: ENC[AES256_GCM,data:UMohgPb72Yho0utkbsQiDkP0OQ97JNvPQtzPSrSYbY2D+Q==,iv:DfVYaPUeol+P6f9zgFklfB0TdXkQzlieHFPOePHrcrQ=,tag:g0LCNCk/woEujTyE+lpkpQ==,type:str]
sops:
  age:
    - recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6aS9rZnhJOGlwUTlqTUZt
        Znh5TEoyTnNMMDFsdWtoVnYwczJZWFNYV0VjClkwWVpoRFhOVWJ0UzEzUzRleENq
        bHhxVk5LdTJjNSt0RWhSTkM2b25pd00KLS0tIHlrNnZBbXNiNTlSTU5lRGp2LzB6
        QkFhaFQrYWswOXJDWURrMUtReUlXMU0KYDOCYZbunDs2h+aOi0P7MJDFL3mLGDu9
        0sfJlVqQ+JO1LjrDrzqncYXeZvTyG6qFn7+qFBNesP7+6p2fNL/WrA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-21T19:16:28Z"
  mac: ENC[AES256_GCM,data:YX9J8+cxmgkngUPYqiU2NmMNudoK6Az1yG03B4mbA0bKt9vrcBUu4AAxf3MO3xROaH/gOLYLlsCAUzikwqywuje8lBQ48K/J5akbUUOiERZ/DH5X+ookIlImfwdln+joKx1ec69OW53CZN4G78+mmRmALGFGsFF/UHHfVY2EyiE=,iv:xUPR7SZfI/Nciga0ALRe8Uzh3jlPpo59sYffDHuv95o=,tag:zL8VvdVV8KsE7UPIMQ8SJw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
