apiVersion: v1
kind: Secret
metadata:
    name: karakeep-secret
stringData:
    encryption_key: ENC[AES256_GCM,data:i0P3gNOaPdsfDcHjfPjedil2SA==,iv:OopkM7i4od3OoWfGlvENMD1Tx5O9O+JXeR4F7k+rqGE=,tag:YhRNUUKStBjNLNgDHUPXzA==,type:str]
    meilisearch_master_key: ENC[AES256_GCM,data:sqxcVOWXE3g=,iv:x124Lkxfxo/N530pUk5JzstVQeuJX/N5VTL1l1ApGrU=,tag:Fp6QshF0dOu9q917g+MOvw==,type:str]
sops:
    age:
        - recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3bDRPWEl4dExuV2NRckZ6
            Nkh2WGRmVUNvMzFUWE9IOEdndzNDSUgva0NZCk1PRWZtL2NYOGZXMW5VNHNIRnlR
            cy9qcmNPdEt1Tk5XNkp0WmN5UDlEeHcKLS0tIFNRRXVkMFhYUXZBSmVsdmdwT2tz
            OFlWMEc0RDg1Y2Y1ODFReXlWbGtjaW8KMltI70a2ZKNRD1RHT3TNTNMPogYcHoWt
            9M1OyOBCPkVt70QZEPDrDJy+kJgyP3FliNVRI0B+SG6CCqUGKbHoMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T15:11:29Z"
    mac: ENC[AES256_GCM,data:YFD0DcPCQj3F9eCU9nCHH4K9dHWP9xSZrW+o+MypcmzdEnarRdYL01G14HjzzbujqHV3wtOfNRsfzrAt6lnuCgnoice+0euN4P6OmONvyYgXn39e3L1T8Z742mhAEUVPQO6K/SPH79jF1wb8AGq2nQu7GFP8oHiqeOFaLEQ53bw=,iv:Tz6m2qtn4vrAtRS3SISBtVSflhOAgdhMve0kEhZMTDo=,tag:D9l8hDerCFeSU41ZOroaTQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.1
