---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - alert.yaml
  - grafanadashboard.yaml
  - helmrelease.yaml
  - ocirepository.yaml
  - secret.sops.yaml
  - httproute.yaml
  - podmonitor.yaml
  - prometheusrule.yaml
  - provider.yaml
  - receiver.yaml
