# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:UM1E3U0oNy5V3Y0KB3NWJZ8cvK7eLaTW5AgZRIKQWwU=,iv:qOTIampY29UXnLWvRHnhAGUJVEiljN73elkhBCpnEho=,tag:fxNmAshpQm/s84PWad6bYw==,type:str]
    address: ENC[AES256_GCM,data:ABvMvBoLip/cSTKK3J4fnrL+7FtSy6wk4w6qGcJgkZoBl51wBolfXpdsfzNNfMyGvTtekmRx5Ae+5OplmELpSNEXawMaxh0qDngy+3fWuMxW9JjhmeXOKaO4JmyZGMewCpiWzW+3gF+oJtRxm3KwPonuGu5kdaC0VA==,iv:1E1R/Dbx6sQnxgkBghtMaYvyJuXvoeDvtqf9omy3P20=,tag:HmC0QoUuI27XM3iT5RaoGQ==,type:str]
sops:
    age:
        - recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2THdCUkVSM052Y1VGb2ti
            T3haM2xQb05RdDdWR3pNd1F4bTY1RS9MSVVJCksrTnFHN0syKzhMajNtZ3FvQWEz
            b29FL0o1dENGbGtTaWY0Q1UxVEVuTVUKLS0tIENRVWtBNllwU1kzT2JVcSsvRGxi
            ZEg5NVFOUFBpT3UyaFc4cm5NNm9CTzgKKn3QrlmsbfXWha2gL5D5Wc4eSYCSjo8B
            swR6vtrqgbMF5+Qiwvd+Wzfh7zzPyfOQj/NAE3q3e8cfrMJHioIoMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-16T20:33:56Z"
    mac: ENC[AES256_GCM,data:M9yRXxZSO/xrjeKsXcH4rDOOSYGfl9pX7N3H6scI7fGeww/n+S/YeIapITkrKacTqFG0GIjF/2hrSOACalUuXFy6uzd1CYKOQuX9uTOLcefVzqNaDm7Lj3SKZa7Fy3VZluu4QQX4SjiwcZxBZTrz+4U5SX7FBBu/OmiiYt3ns7o=,iv:yhszSRKEHSUmCPZShUhnR7OR6RkYlHeR88gzHvdxCyc=,tag:tXWDc/YZ9rbhK2pgo+bo6Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
