---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: external-homeassistant
  labels:
    kubernetes.io/service-name: external-homeassistant
addressType: IPv4
endpoints:
  - addresses:
      - ${HOME_ASSISTANT_IP}
ports:
  - port: 8123
    name: http
    protocol: TCP
