apiVersion: v1
kind: Secret
metadata:
  name: sonarr-secret
  namespace: media
type: Opaque
stringData:
  #ENC[AES256_GCM,data:EnaI6yrhrKwaDtqCvBFWyl+dtBN/QCp8Eo0KXngTSOqIFvgBfcKUpilojiO/vFL1Nbit,iv:rVfjr2cYFBR7WQ/ds8XTni5i/IYNOtJqvV8Eyj7sNxI=,tag:fuxelDxg9KnSVpaT1rvSow==,type:comment]
  SONARR__POSTGRES__HOST: ENC[AES256_GCM,data:aaJWrvxGjMarGz5FRibOEWqMjHL3t3HTRZPMqw78EMk7ajk7R9uIoQ==,iv:Dmmr7RHhvT9iDV/CtGktVIu5tQUeUiBMTi1IL8Z+HIM=,tag:ZtUdGc5ZewaWE8s/AD9o2w==,type:str]
  SONARR__POSTGRES__PORT: ENC[AES256_GCM,data:XVgHdA==,iv:2Ym90/+g2tkt2MF1NDmSIob9vcgRwH1GtNFVFBxBq6s=,tag:e0WL8pBB9CRgwjvUcFRcOQ==,type:str]
  SONARR__POSTGRES__USER: ENC[AES256_GCM,data:+qMzNCf1,iv:eCMKa0Cr1dXGRG3ZP+56qI4OEbnQ3KWjqzzyXmKPKTg=,tag:9Ada/UP19ZOtwwvP4ex38Q==,type:str]
  SONARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:p2CPqSLLdRY=,iv:CyfC/3n2nxaXevUyRB2ovOwQPoXL1fIoZ852lJkJFxg=,tag:8Rfs94r3sUi9mBDjGVie3w==,type:str]
  SONARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:WoUG/SVi,iv:yCEC/ay6TDvmuNWHJYAhdFaqPvYUm4u9ypocMr2A2YM=,tag:WgBovC2egTCUoCzVgaillg==,type:str]
  #ENC[AES256_GCM,data:V7Oeihp/zPTwLNuFJDu/uiTjBLb6NfUPhr5mNnsgvHFqNHAxRT7kElwHCPahZRl7Xwpmkiow8g==,iv:vHQ84jEOqzvPb0uif22aS48Bl1M8n0uinPWp6uW0Beo=,tag:Vqy1kaUUCHUioAP69Nqe6w==,type:comment]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:9YZ1LxA0,iv:PxLqRwzlz6/gAyTxLqpRlDUN4+0bXNhEpnDXJbZYnsk=,tag:sRHxhxjZPyDLFGLBazemcg==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:z1cfJh6DlvkIqxxvYFLNvFjHhua/nleJgQXDu7yz/D/vzmdktEAq1g==,iv:TYuniwt+aBIoS9iLIjgalLYO8yWNv/XwqXX6ERKbvro=,tag:F8x8jG72Fi7Li4Qz5xyqvg==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:UQJ3VT0/,iv:sUCwYmAH36sQt/eQ4D3msrsCa1kI7eUMPdf/DFMumfE=,tag:EsApHoC00Q4+ejTGpaYCIA==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:KycggHJ+0VQ=,iv:k5wWOXjP0bzKG0GuAuirOKrRD3ROHfDt6VqpVuAd5Y4=,tag:vxmSNnvOWiMqenRWtstwaA==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:akb9lXGYhqE=,iv:Tr/0D5zFyJTI6/d4Cbf5uUa+jFeBRpvJOaKu6voXKzA=,tag:M41vE8qsj7tjJoeVff+ckQ==,type:str]
sops:
  age:
    - recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxM0syZnJPc1k2d2JRL1Nu
        QUcxU3BJaEoyMGVLbEJzSitvNEgvb1h6N0ZNCldXK1RTZU9QTTFWaXR2UjFyT0JN
        MENCUENUTTRKdjZwZGpmckVENHpCclkKLS0tIGd5NHN6dEkyN2xNUVF5S2cxbWxi
        YmkzUHVUNjloSTcyTWZ3R3JBbnVMR1UKF4hGCYkGeBFSuO2pOHFHhM6DGWUVW4yY
        tq0Thgve54/cFOEAANreA3DAla3xnTxOaZXB0yAnyhTMvnFD+2Yb7A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-10T19:35:14Z"
  mac: ENC[AES256_GCM,data:IA9yYmc44BSJpIMNV3Naq70H8rjS2DI9pgxPEiahr2+XftqE6C5GiLLDvkTUlDRf0qSwgOj+6q6CYPjjWKpVB5f5rIkw6lKjUhQpuG5HyTxFL50T3/dpw1jQq8ZOkEBtBN5qGa63GOsb7VOkSEjeYcD/ZwBe5MpP2b7CK96ZgzQ=,iv:kTRveEsFR/SlKVLf4vfcAQmT1AmoYUsFZT5VBmC0ZHo=,tag:KOeTKUod6qZ3IbYlNuTwlA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
