---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: p2pool
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 1h
  values:
    controllers:
      p2pool:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/sethforprivacy/p2pool
              tag: latest
            args:
              - "--host"
              - "monerod.default.svc.cluster.local"
              - "--rpc-port"
              - "18089"
              - "--wallet"
              - "$(P2POOL_WALLET_ADDRESS)"
              - "--stratum"
              - "0.0.0.0:3333"
              - "--p2p"
              - "0.0.0.0:37888"
              - "--mini"
              # optional: reduce RAM
              # - "--light-mode"
            env:
              - name: P2POOL_WALLET_ADDRESS
                valueFrom:
                  secretKeyRef:
                    name: p2pool-wallet
                    key: address
            ports:
              - name: stratum
                containerPort: 3333
              - name: p2p
                containerPort: 37888
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 200m
                memory: 3Gi
              limits:
                memory: 4Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      p2pool:
        type: ClusterIP
        ports:
          stratum:
            port: 3333
            targetPort: stratum
          p2p:
            port: 37888
            targetPort: p2p
    persistence:
      data:
        storageClass: ceph-filesystem
        accessMode: ReadWriteMany
        size: 10Gi
        retain: true
        globalMounts:
          - path: /home/p2pool
