apiVersion: v1
kind: Secret
metadata:
  name: p2pool-wallet
  namespace: default
stringData:
  address: ENC[AES256_GCM,data:Vb4PIQ5eN8PprK2p3PRP+21512hjU+bHB3HANgW48UR8tD1/wLKFSClHy19p/Tg5aOdGtZLGgee2MtevQqgloBKlyh6pnMkz6rmcwtu2gcQdqORwprU9+0V8RNwlJvM=,iv:il+5GF6FYSGAbHApPuVuZT954qMFoqZkcV0JUC3m1Vc=,tag:JDNhrQzNe/KDWiOucGfn7w==,type:str]
sops:
  age:
    - recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ZXlUU2lISFhOSFNOdjJ4
        UUlJampHL3dDd3RPQTdwbmpzZ1VzTG5IZVFJCkI1NC8wMnYzRmdKTzVNdGUvbWlV
        ZDhIZFcrMVd4TEhqbHpiU3N0bjRXdlEKLS0tIHA0SS9TYm9PSUVHWE9nSUlOOHYv
        QTBpVFlZSUU2OTZpTmxnb1hwYnh6UEEKa2HuU2qq3zVF95PnA6D2ve8A65EbRoOE
        hGY950vMGpleoL5DhBu/TbgTXWhlwMhAsEmyRh88pf5SOEr6+oQFGg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-15T15:51:02Z"
  mac: ENC[AES256_GCM,data:7Sn6FdqoqXMkFnRbCsgkZL/HpHiGWi4CFUAx0koY4hQGutICGvbWlp3XqERlMtuifQjkpxzHeG4adMVLfVm5gRI2CmVf1RUucd98+i7xSRSH2Vx4QA6gMAABJYVnfKHJsvgQzp2wFuVeWg37JgxCGjlE01CXeBxOXoS/QtXFGeA=,iv:RwER3xvlNDYyYkV0HcCxjgWU0gYFC9X9us9KBCVI5o8=,tag:1d3wblbfa30bSNINw3ZzeA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
