---
apiVersion: v1
kind: Secret
metadata:
  name: toolhive-kubeconfig
  namespace: ai
stringData:
  kubeconfig: ENC[AES256_GCM,data:aQ9cRVY14hVNu8y+qjM/YeDJBw7xxHhwzv738XMk0Ig0CfwKjVVmfkDsjolx4fj7oLEWGjSFolNI7f4jZQoPnSFb1D+oFlh0+dr5rh75Ny4sxDt8OnB3TN/oPDTZZ04U5IUgKs/4mIYcPtPuGxfsMzOq/98bRHpyk/NWxYfIy/JtFdoPRlCwRrNfzYB8Ptlfjf64DXi/6M6SpFWipKaqSTqkhb/VobaNgxI8Jw/FCmj8HjvdcFWZjV5336aJiA0UwONv9z4/fR06QG0nHr/tyAfE4jeM8otx5KXP35JXWqOuVEeX3inFwU+W9LcwBMi6sWw6oXGZiWlqzxoQ0QRrcEQnfHER/wfB5JFUI6cy8V0Iqp9wrctZlITTfHRjmjc42P31WTjmooHnFe8IEl80rhtJ8PriKV4FBVCEBvtnw3jHZvPj9KXlclqtAT/m92Opkg==,iv:dxgMeOAxdGyHZ+scHD1HTBs6cdaJNAg0u1LMirPIxYk=,tag:b405azWyIhpU+osAwfQPnQ==,type:str]
sops:
  age:
    - recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2LzIzdHFtTkxpc0p3ZHB3
        T3ZqM1JYTExML0g5R2Y4cUkxZ0FyVFdFL1JZCmN1NzhhZmhVaFdUd00yYTZNV0xl
        czNsUUk3MG5DUGNDSTlpUmozNkdqYlkKLS0tIGlOSjIrRWxqV0FIeUtSdTVkQ1Mz
        aG10eFEzaWUvRU44blhCZDBPak9jd0EK3euwaxC1hmyWBZ5z2TJ4LAU+/aWYfNB+
        lNosvnAVWcAjxzwanyGyfPQGeu9yWID3NzjxwTUr+WJZwiqzacGfGQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-21T12:29:10Z"
  mac: ENC[AES256_GCM,data:0klwfk6Uq1dGuOjmlrhXvqfjsUk/Zje22wm2IqvvE1riufnWwcsmTWrXDFEu9xqo5MMTpy5HK8VUSDwpVIaVfpqIPH80TfX0VYy8JsaT5XQvKAfdYAsTkXwXSqTVjcsPmm29Coyw/VU4GlADss5HR9CgjHt0JL7RWd2TYH76M1w=,iv:o6POKT45U7sSvaC2xyUvtqbDTla4XczvGyZHIBZDt3Q=,tag:2/DVuBqGc6/Iq3IPo62GNQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
