---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
resources:
  - ./mcpgroup.yaml
  - ./virtualmcpserver.yaml
  - ./karakeep.yaml
  - ./searxng.yaml
  # - ./homeassistant.yaml
  - ./fluxoperator.yaml
  - ./grafana.yaml
  - ./github.yaml
  - ./sequentialthinking.yaml
