---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
resources:
  - mcpgroups.yaml
  - virtualmcpservers.yaml
  - karakeep.yaml
  - searxng.yaml
  - homeassistant.yaml
  - flux-operator.yaml
  - grafana.yaml
  - github.yaml
  - sequentialthinking.yaml
