---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
resources:
  - ./httproute.yaml
  - ./mcpgroup.yaml
  - ./karakeep.yaml
  - ./searxng.yaml
  - ./homeassistant.yaml
  - ./fluxoperator.yaml
  - ./grafana.yaml
  - ./sequentialthinking.yaml
  - ./secret.sops.yaml
