---
apiVersion: v1
kind: Secret
metadata:
  name: toolhive-secrets
  namespace: ai
stringData:
  HOMEASSISTANT_API_TOKEN: ENC[AES256_GCM,data:XJ51lwGmmfI=,iv:JzxXzObgzxPfetUe0pzst8v34/1h+glE5JGvk87r1PM=,tag:+OXbZ7D8TaW+ebroLb/PUA==,type:str]
  GRAFANA_API_KEY: ENC[AES256_GCM,data:57682ecnYmg=,iv:nqL+cy5BrwenjqJ/p4L/6k4vuBgqgiMI24X4HviMKbs=,tag:T8/qwvjU2KmIZLU5BrMWeA==,type:str]
  KARAKEEP_API_KEY: ENC[AES256_GCM,data:UogJvuiNLMw=,iv:vuT+J06S4vlGE+rI+xWCMYpix80/+p/3jaSihV0P7VQ=,tag:aQlYa+2QDBJRBy0DO8TzZQ==,type:str]
  KUBECONFIG: ENC[AES256_GCM,data:aQ9cRVY14hVNu8y+qjM/YeDJBw7xxHhwzv738XMk0Ig0CfwKjVVmfkDsjolx4fj7oLEWGjSFolNI7f4jZQoPnSFb1D+oFlh0+dr5rh75Ny4sxDt8OnB3TN/oPDTZZ04U5IUgKs/4mIYcPtPuGxfsMzOq/98bRHpyk/NWxYfIy/JtFdoPRlCwRrNfzYB8Ptlfjf64DXi/6M6SpFWipKaqSTqkhb/VobaNgxI8Jw/FCmj8HjvdcFWZjV5336aJiA0UwONv9z4/fR06QG0nHr/tyAfE4jeM8otx5KXP35JXWqOuVEeX3inFwU+W9LcwBMi6sWw6oXGZiWlqzxoQ0QRrcEQnfHER/wfB5JFUI6cy8V0Iqp9wrctZlITTfHRjmjc42P31WTjmooHnFe8IEl80rhtJ8PriKV4FBVCEBvtnw3jHZvPj9KXlclqtAT/m92Opkg==,iv:dxgMeOAxdGyHZ+scHD1HTBs6cdaJNAg0u1LMirPIxYk=,tag:b405azWyIhpU+osAwfQPnQ==,type:str]
sops:
  age:
    - recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkSWp2MVdldUs1QzBEWXI5
        R0xKRWRPa0lESFBkdkNickxreHlPencrdmtJCkZUU1NQRzRhMDR4czZSVWZDYmpO
        YTBKSWhLSDBxdDBqVExrSEozeDNRNVEKLS0tIHBCNnhENWxRZTRhL3JWTmxzaVo3
        Q1J2UTh4cHBodVRFVDZMNXFqVnFSVG8K4xXNAcOKRr4b7YOZKmrYSO9UE4/EGync
        RLmMqqkFWIQnPMNIlCyQ+9T4I/U+E6VW9Ri49l197Cq8RyUllBgRWg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-21T12:29:10Z"
  mac: ENC[AES256_GCM,data:L4dDr4HxQ859l5JDpvMIG5BgSJ21sP6jrMWf0XPQcLoN2aX13DNmAHj9aTYGNMymLwHN1OkxHllBSiZlXWYGQqH77fM3/Gb3pMaZvl7sepktj0OkcxpaP09RFart+J9lUxIn6u6R3Xjs1PNT3qp30CD616EV0wMK7YN3Hir4M/M=,iv:ISAaSogt8LK5KXSyBT9R+5gmuNWXvPH8AOAq+AkDCK0=,tag:AuwoRlir6F9J3STo6tSAbA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
