apiVersion: v1
kind: Secret
metadata:
    name: gatus-secret
    namespace: observability
stringData:
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:/r365zaBlxG+G5UB5NSr/RolqN+8cjGV3d4vqxP6RiruPWrBqUf0UQ==,iv:7QBES+GTjrLJYf4R3ZtaNjH4OdUeUphWg0y8rCiZQgY=,tag:I4538OE13XdIl96KV37eXg==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:F4fxU2E=,iv:kIZ8cAk9P+CYSuRTAVHReWrj7meToU1PjLqFkNXN8KE=,tag:fCLPNaTgGPdmBUDC+RBDHg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:WkH8PYY=,iv:zN760dvWhOrMIk1ppY9AMMTYq2871pOPVIRU0JHz8Bg=,tag:WwotR0CeqtdwlRPCPID+uA==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:caqOKNgbeTs=,iv:kGfT8Sn4HiU+csBpjfGwVngipw4r0Gd84uyJ+FRz0ic=,tag:SJa6grC51sjTOuRX8azv5g==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:OJFihmZ4X58=,iv:aNhCONYqmwPXigbRDNOq9f72ptuEAWYaKF4rhQrI74E=,tag:WQAQ5L+LT2GW8pciB5oYGQ==,type:str]
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:429MPmHpkNbblWLx8LqLMKdQojXsthBMy0GSrBeeIdRIH0Ul725kDtbq65TS6CnXGI17uJkqMwNA4+sNCp/lbuMmyUVNy4zHG4z/qZB+ZhovoBlusCrJ+hphjGfYJ7mbkehHBVzdj7NkYMTrK8nP/vLgXTkGHnnOeA==,iv:o968amUxRwHdfCN/aUa7QpJgbx9JBaftIl2RwenV55k=,tag:EuhDmJN4BK0WNvZ10vgdNw==,type:str]
sops:
    age:
        - recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzd1p1SHJiQVRYWkRlQUUy
            YnRzNlFSQnluZ1NQdVk5Z0VmUkU0dk44Z0gwCnpHbEd1R21McTFkMzBrM0U1U2lq
            NmZKQ1RuVGFEdzJHdEw2MnN0Zm1PcjgKLS0tIGNCdkhDWVZoT3ZlVGUzd05CajVD
            OHlHOEE4QjlweDRLR1BTanFpNGcxZlkK+WWzdC5kwSbUpcsR9spN8G7V+9shxkdQ
            exKY5OmR73kEUkv5YuUgur7ZXWPqMptbp/7izAZqQ+Euf9yf/g1u0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-11T13:00:31Z"
    mac: ENC[AES256_GCM,data:AsJxRKtvmqCsnSO9Gw1JL51vTjM80AIUXv5BmAUPOyCVI+s0e7/hH0EZF9U/xxLImgzrn/tIuLUTvvLPeOBPWVjAeP+A+qgU4pEQSFE2fdyKVioNMJ1ykJ954tgB4BGrGfLjqLVIDVSJTBMkOI6f8N3OWK/Qj1Dlcot+352I6N4=,iv:FcJl26mKTKpe7wkG3SY2C0n5S4RvAlFtGzAlsLHOrzc=,tag:PKP68h00hcvfKpVLwmh+cg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
