---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: homarr-database
spec:
  sourcePVC: homarr-database
  trigger:
    schedule: "0 * * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 14
    repository: homarr-database-volsync-secret
    volumeSnapshotClassName: openebs-zfs
    cacheCapacity: 2Gi
    cacheStorageClassName: openebs-hostpath
    cacheAccessModes:
      - ReadWriteOnce
    storageClassName: openebs-zfs
    accessModes:
      - ReadWriteOnce
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    retain:
      hourly: 24
      daily: 7
