apiVersion: v1
kind: Secret
metadata:
    name: homarr-secret
    namespace: default
stringData:
    db-encryption-key: ENC[AES256_GCM,data:PupvW93s1OdPIkzFdgnizWAtpHl2IPq2jFOuqGye4418QwJHDnEvQGePySwltS0TcZ+AfnoHFqC0Do5LCq7Thw==,iv:kE5ooWlUcBXBRzlCwklHtCMzszJukEpE2sIOTcQneqA=,tag:ZreruHSOnD3kigkGpwl5GA==,type:str]
    db-url: ENC[AES256_GCM,data:wlD/k1MiNRwJqIk2pnoHASxMcWtoGq0qUwyOf/vQlykJcDsawFD90k+xf9TTnAOcFFNBq1B9LfeZ6OYyS86fAcPP3TqNe7MBhEpmQzttaI08,iv:esiXzD+TF1QM7fV47gGHN+QOKGmDpkvCqpSwg1VhytQ=,tag:kk/YzXzOd6cWI84mIYYRhA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:3hLeZq/4/zVUS9xGkVuPysSXXap3lt3HTGIWURoApjil5gJGYX9j+A==,iv:QLradbwOa+IK+byz5+IHz+IaKuPwFPzYepL4sfBGRyM=,tag:u2wmzrqSMts9YmmNprx8jQ==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:2jD93+X/,iv:yY/LOvYGhQFMmbgqpJqrTUm7XcGxGanluMR6yC/JtF4=,tag:Y5YrzOK1jHPlL3kFFp3I/w==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:MsuDHNYf,iv:0hPU9kI4YdehTnNZpwc/rENwOL7pL3U0ewyj05eroT0=,tag:vaDfX9a7cD+Rn+n8Bt7ZHw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:Og2fQ0hNHbs=,iv:44ghXSkeSXot+ZqP2IMFQ6OY7A+07QLtS2JJOiwoOiE=,tag:lalf+6H6H1TnoJLpxzBEvA==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:fxfhmtnoMvMVgnzGhQkd4fGYJrCy9FyGvwHiElAmXx8XnlTGsleMTmRp67Tj1zdIuu+NreIW65UjEuLfF6oNcw==,iv:vbK98BHt+Qml51PB8W3SCAUmIZQ/PrcsvqzLMkdaJr8=,tag:7pq1UzatOafhYkvmhHMspg==,type:str]
sops:
    age:
        - recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4SVNLOTBoTklWdXBGdmFN
            YkoyV2ltdHduRkpIZHFRL0VQZ095M3RiZ1FzClRobUpENHhrNHVTN1pEc2c0dGIr
            aDJzOGRMTnlBdFc1K21ya3dKMjVuK3cKLS0tIHlmbkNwZ1pDdzU2aUV3YmhjMThO
            WnRYSmJaOUFkZWk1SVhCRTI3V0NCTEkKgaxFd2WDa5Jhwa+6cZpy4/DapgbWopGF
            G5ZGq7FOzp8Z/dFMyXCzM0JtgCPaUkJ+K1Em/0/VlAvP8gpVNBDhdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-10T20:25:12Z"
    mac: ENC[AES256_GCM,data:NuqoH7urm0vFrI3R/qmgZw5V/JuD8YPfsNjHjCGGu/P5Z/zXOAi0d/W2I67Th4GQP9KMM5UcrgIJckrg5BWRAVFpMAzOoJcmy5GAZsia4UBGUpKcus/XwM3xD4Owx7dcVU3tPkF81pcMjLaA7uu/Z8FcfNOp/xidz4d9cv4u4Ts=,iv:Tb047DOGe7WVjeTrdrdGtmPhbIO6xGAcSzfIrZ1HdJE=,tag:efkNhn0UTbDdJiJ0yITxBw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
