apiVersion: v1
kind: Secret
metadata:
  name: homarr-database-volsync-secret
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:6LkfkzYTt5lmheKuhUs63/aGs7Zv9CzSgXbC,iv:03dEyQg1unoIvriB6zxvfXKUrBybzZ7KQv3EjP97SBo=,tag:28SQoTORwQws6iSsu2POlw==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:ZxjR+KfQ06g=,iv:rIULMWR1KE592SU63pxSumAX/z2imzqvdgjZ/0glbxs=,tag:2qJnfDRxMbP5kW/WkJDJQA==,type:str]
sops:
  age:
    - recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSVStzbERBSDZvcE0xZkk4
        OXZzZEhJTng4UUE5M29obUdHVEQxQUh2dG04Ck5zQmtWYkVqTm11ZjQyS1NFTmpJ
        dWlxdm9lL3FoLytibzZyaE9DeWhJdDgKLS0tIGRrQmpFVm1TR0hQUGhybG1QbHpa
        cm50OXkrOEtYb1ZxTE1IY2l4TVJ5d1UKxnTjWLCPWhdfo7LX2OHbPm8lM2RvQ+Ep
        EFKaOD4N85U48Elh51O9Es6fsasLzcTAKbzcMdbUOEUfdkxl7XusEA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-10T19:22:20Z"
  mac: ENC[AES256_GCM,data:YUWSbNV9aa2Ih/gDH9vniVVVu3I1BbekLx+OPhC4Czi+3TUItP5a3I5p0xB9/lno7v6tuVLZrxANdYzZQKZQ+b4L2YA+hEGywwdTzMx5VtfOfK+1k11laavRoLMcHkuHZa3bSpCLALS6JCbBEHr3hC5ATi3Ai/MI/S0HI6relN0=,iv:tJZjyrRcrn9Ud5Jr8JFj5q9GTH4ARfG6bqRDM43ey2U=,tag:SRE3V+cSspq4yet3sksnwA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
