---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

components:
  - ../../components/common

resources:
  - ./changedetection/ks.yaml
  - ./dumbassets/ks.yaml
  - ./echo/ks.yaml
  - ./homarr/ks.yaml
  # - ./immich/ks.yaml
  - ./it-tools/ks.yaml
  - ./karakeep/ks.yaml
  - ./nextcloud/ks.yaml
  - ./picoshare/ks.yaml
  - ./searxng/ks.yaml
  - ./spoolman/ks.yaml
