apiVersion: v1
kind: Secret
metadata:
  name: prowlarr-secret
  namespace: media
type: Opaque
stringData:
  #ENC[AES256_GCM,data:oZseR6fpwk5LVZofjkdR+hl8bBrtHxI7gimOsJ8MiIPPuF0b8YGpcTRzjqG/EgE131g2,iv:0XzQ4gapTi6weWVpYs8+QYkchajamLEJ35HerQ/GSxE=,tag:YzxiDZ7jQtdYOqJgjOrbVA==,type:comment]
  PROWLARR__POSTGRES__HOST: ENC[AES256_GCM,data:9lER1SgbhhKQEfIXen4MCLEvDjIagQvU+Rqt4eOht7k4i9iVck3jIA==,iv:C8ASOrP+G7fsArBJznN9oI8wd4K6fOmhc7PtlpDZlHk=,tag:E4dpD6/zrbKJKiTf51AmVw==,type:str]
  PROWLARR__POSTGRES__PORT: ENC[AES256_GCM,data:+XpttQ==,iv:yawhadD+90yxd+pMGS4Zaqrwimmh6tkNKPr9+N6Wn60=,tag:6OvVx9xFFOVExMvzlh19Yw==,type:str]
  PROWLARR__POSTGRES__USER: ENC[AES256_GCM,data:r3OW9MXSeO4=,iv:07vB6FHHCX1FG/c0jd5W5HO/1uN8lZ+Tnqdf4Xk+KPU=,tag:FofpdzCS0HrzpHfDQcO/tA==,type:str]
  PROWLARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:isDcbBuqODw=,iv:Z+2ACBcXZahhn+GbKnGSU8hSzDIpMFn+yx98GpN8ZOY=,tag:X7NUgRRmRS47ZDkLqMBM9A==,type:str]
  PROWLARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:AeP9CiylI88=,iv:WF+t+hEmcdirIjWYKuafbxSPPTYLI3ROkjJVwPkrtE0=,tag:eEpwJlvo+PLpXmxiqAOkCQ==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:PQ0ZqxZ4GIM=,iv:0U/jVggGWYXME27X93FTet3k/9aYdhXuJOmaVuKgNHs=,tag:BywIliBAsVnem5Bor8r9bw==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:bzJWP9eNGBk/JQ3ulIElSQ51yB0DgryfOIblwySA+bHVV6/QxT5B+Q==,iv:6wws07ikybn0fTPBYZ8jlS7L/e6mjXj7D+pxMQS7bvg=,tag:MINXN894F4Mbg46blRyAiQ==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:JmsERV6zBgo=,iv:+z+IFA3d4sXc15OXiEWY28KJJ+QaryfsUTO0Lrhe3nc=,tag:Cx1Actj0qEbgAZyzlZrO1Q==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:zwB0CIq/dI4=,iv:JUtUT3ALsXLp1V27baxWpt3hx8Ib2X27yD5kSTdhL4A=,tag:YNpR4cNKZprmjpx8yC+C5g==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:SDRovI7vN94=,iv:Arr5Q3SReBzTFq05m0epOcp+xzsG3PXKx40ckjRk5sI=,tag:NED12hT97EDJomQr7ilUPA==,type:str]
sops:
  age:
    - recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2WFdYWWZzYTVTY0hkcDRm
        dTZQOVZ5eFZTK0NxVERVSG9oL1NyT05ZL1JzCm1ZV2tmeUNsQVZydWtvVkZodmVV
        cTlXRTlieTE0em85YlBYcGN0STVxMlEKLS0tIGlSbnVYVHE5RURUbisxVDdlV3ZQ
        RjRYUTVWS2ZSK1pENzFvOS9WTFhBUjgKupk0EeHRErfpG8lrYkksr9OmgOTalXJb
        b966I64pWQdG7Urb4pNIOyHpJMBe6DX1vvqQ8aszXNi8UKV6ktoJfw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-10T20:32:20Z"
  mac: ENC[AES256_GCM,data:/0ZRFdgIA4+Y9namd6fEtooDv6HX/iSaFPoALJYkq1ShVAhN/EK/9RcFiEv7hvi3d1fJsHMEdN773sGX/Fc6DNNQ3NYJoK3NL7KBXePF1N+PLRk7+NVtebY4isIxO/WZjIIst4ac61FNwxTiF+i+70ogXygWdQLwf9J4T4fLjew=,iv:1dcm5krt/6MyOHEMpzxwd+dYAQYHeJmKjG3130y4bVc=,tag:fl4975xiS0RG8Rzjfuf7+Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
