apiVersion: v1
kind: Secret
metadata:
    name: scraparr-secret
    namespace: observability
type: Opaque
stringData:
    BAZARR_API_KEY: ENC[AES256_GCM,data:TRV5QSkLwrHHkuYIooV5i+L4nNgqUfi76od/h9Zgyx0=,iv:59xt4aSz/Y+8ErkytJdwj5sBf4hqRTS5oEsbzQ4/mi4=,tag:/a/l7kEZYGfSOEyrMDfdlQ==,type:str]
    JELLYFIN_API_KEY: ENC[AES256_GCM,data:e2iIU3BHLBM9sBGO+glXCrAaYnX2RGnuiva3Io4uZN0=,iv:BVl0JUZFyRLhtLNntx6OFxJOxo3Bef5vYUXKDKeHupE=,tag:Jd3XiPeC/5MbtArA8UOe4A==,type:str]
sops:
    age:
        - recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZEx1d3JmUXpZMmQvaGtt
            Yk55Z0toQnVpTDNhK2lVSFVhWVU0Nyt2R1djCi9hQ2lZRjF5MnZNNC9nYzZ5V2pL
            V0FBMXpFOGt4UUpmMVRGM2k5aXFFejAKLS0tIHlWd3UvWFJDTGxnUTUyQWZPbXkw
            Zm9wT09zUWJjOFhkUkJ2ZDgxSHV5WUEKDWH7/7QUpUBtz6QgV7yd19SLgyUKFQnI
            PVDPpfGzPGsxvkJQQHK0xSbpRIpKsn1Bhj8M96mbG47OTDfTigHzPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-13T20:27:21Z"
    mac: ENC[AES256_GCM,data:AvTvU3DQCC+LIn4ASh+Jl/o2ihaMn/1lckBLcs8WpxHtCg9KnVEclAI2Ia7z8aqw7qV5XYMvc57FIIjvvTJ59V45zuIPRAweB1TBl887t5FJXmmcggyn8W/Z3RSCaemBo26QH503I0yDVcfUGcIxHkSJQkztB6Z4Hk7YGGUhcoY=,iv:QhgH+LakcLSOIcIDebZ/0BDhBiimr3igAxcayWg2yoU=,tag:Nic7a62B/Aio/LYiQI+D6Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
