---
schedule: service
action: remove
remove_from_client: false
radarr:
  - name: radarr
    url: http://radarr.media.svc.cluster.local
    enabled: true
sonarr:
  - name: sonarr
    url: http://sonarr.media.svc.cluster.local
    enabled: true
