apiVersion: v1
kind: Secret
metadata:
    name: n8n-secret
    namespace: ai
stringData:
    DB_POSTGRESDB_HOST: ENC[AES256_GCM,data:QraepkOd/qdYA7+imsaB7yzlTTsO2uMPrJBOAsux1JmQtMzKOfKW8w==,iv:kOYaqEeYGpFtHDX12kiuorFgbBonsLpepi4Ks7BHh9k=,tag:X2ylKAj5JWkzwzTSxiWRhQ==,type:str]
    DB_POSTGRESDB_PORT: ENC[AES256_GCM,data:bERaDw==,iv:mRG/CQkLVVQr9Wk/W88wL6v3Q6bfl7eDr3nOJjOE6pI=,tag:szkXXm8N3WUAs+mloI9F2w==,type:str]
    DB_POSTGRESDB_DATABASE: ENC[AES256_GCM,data:zh6S,iv:8MUMTV2mPrRjhf0P/0/PdnNUUnfC6mH15YSGsWm2gkc=,tag:ZkFm80lY79u0/9Bbd2HF1Q==,type:str]
    DB_POSTGRESDB_USER: ENC[AES256_GCM,data:usEY,iv:+Aw4DaoBr2s970T+593fVIszwvPDrIeyTx1Wd4LHGwE=,tag:Fn2ekkZr0DyRvHEz3wstNg==,type:str]
    DB_POSTGRESDB_PASSWORD: ENC[AES256_GCM,data:5hY2EhndvnE=,iv:D8JpRIJRpYl0quCl/5LDYyA7Kc8oz2UZQTn+m9hOVNA=,tag:RBaZVxmL74ckZDPrSJNBWg==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:4ChA89QSGCH5E7Y8q0ArAjVBV6+e0tdvLMRUI9EhdTAIYEmjj+LNuQ==,iv:Wn9Xf0dwgD047gBurekr8vAOdyn5eq/Ym951Po018IA=,tag:QB/L+Y09SFvXsawOrg4UaA==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:8W/b,iv:13ShDHthY9Nvib834co0K/fxW2B7rJI9u4msHOjP3o0=,tag:Dir3psyjv6X/fQ5uwqoeMw==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:Aofo,iv:RNYgYnxw20kkcKHqjO4dfO9aB1RHmnkJgkjAnbFoGPM=,tag:3E4eU6JQ2FQb13EXYXwg4g==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:dNGvOVZlKsE=,iv:oQRJTqBo0BPrYf1ryciB/FAcANRZELcrttgezAKW8ss=,tag:jb7ss118mBADHfbOd/eMSA==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:dJhKY3jjSKo=,iv:eoWcNIlWiWJZc3G3/LMFHaBpyEyhWhJrj2nqjKTvWcA=,tag:2kxByPA/HjiwsflqDI061A==,type:str]
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:8CmQKzjH+Pw01rz0tOovPrCkdgjYJayKqw==,iv:pSQnr5tSQ2kEqkJif3Hiw7CtpQNUFhmIVuRQ62o4smo=,tag:oQuP8ToRBMNWJmDl+E67FQ==,type:str]
sops:
    age:
        - recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJR1FiZHk1RHp0YUpFZGxV
            Q28rSTFyNm9pR1g1cGpFZ3NRbHQycEdCY2dvCkF6MG1JdUNwS2t0cTU1b1FpRWRG
            endTc3l5Y2hYMkhDV1F5cENRbW5vamsKLS0tIEpQUHJIaVg1RVhTRmhYMi9ITlFo
            NlhtMmZxOU9oY05qVDNjT1hMa0wrR2cKlt6OSs5wV/JNPVabw+1IebIGRG6DS7Le
            lFBLu8ch7n3tz1pjja9D/th7Rcl7WV/LY8TXE3jG6UWCdFyR2fuRMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-08T22:26:15Z"
    mac: ENC[AES256_GCM,data:Nu0AzEn+Kpw14/yykMi0hGWfhAHugeF6fSqpBnNxujL6BtFYIQ8x5J88b72p/YqCRk3v+wFl5aTMZDbfuq7Sil0BCVwl0bJwIva658jopzDNj7p2sWIBgcAvuQ5TwLKrFXxmDu9kgapFNs77M4AznIxDfxhPXxYGbpZCF1tSJDg=,iv:GtCekQX2f/Qelu7n7rt8yAkEVS1GgzlwBH5nKo8sEDY=,tag:DfQuG6IHeG20Pybh1VErpw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
