---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vpa
spec:
  chart:
    spec:
      chart: vertical-pod-autoscaler
      sourceRef:
        kind: HelmRepository
        name: vpa
  interval: 1h
  values:
    recommender:
      enabled: true
      extraArgs:
        storage: prometheus
        prometheus-address: http://prometheus-operated.observability.svc.cluster.local:9090
        target-cpu-percentile: 0.99
        recommendation-margin-fraction: 0.05
        cpu-histogram-decay-half-life: 3m
    updater:
      enabled: true
    admissionController:
      enabled: true
