---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./secret.yaml
configMapGenerator:
  - name: qbitrr-config
    files:
      - config.toml=./config/config.toml
generatorOptions:
  disableNameSuffixHash: true
