---
apiVersion: v1
kind: Secret
metadata:
  name: qbitrr-secrets
  namespace: media
type: Opaque
stringData:
  QBITTORRENT_USER: ${QBITTORRENT_USER}
  QBITTORRENT_PWD: ${QBITTORRENT_PWD}
  SONARR_API_KEY: ${SONARR_API_KEY}
  RADARR_API_KEY: ${RADARR_API_KEY}
  JELLYSEERR_API_KEY: ${JELLYSEERR_API_KEY}
