---
apiVersion: v1
kind: Secret
metadata:
  name: qbitrr-secrets
  namespace: media
type: Opaque
stringData:
  SONARR_API_KEY: ${SONARR_API_KEY}
  RADARR_API_KEY: ${RADARR_API_KEY}
  SEERR_API_KEY: ${SEERR_API_KEY}
