---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: internal-vaultwarden
  labels:
    kubernetes.io/service-name: internal-vaultwarden
addressType: IPv4
endpoints:
  - addresses:
      - ${TRUENAS_IP}
ports:
  - port: 30032
    name: http
    protocol: TCP

