apiVersion: v1
kind: Secret
metadata:
  name: immich-secret
stringData:
  JWT_SECRET: ENC[AES256_GCM,data:SrftPOuRDkE=,iv:cH30BeMrsIfoxeQV17Du4IVOXGkOejyXEHkQBmTIl6o=,tag:L85BhpN6rOWYjoragZPb0A==,type:str]
  TYPESENSE_API_KEY: ENC[AES256_GCM,data:oeGrUjlO5Uo=,iv:FOrcbt9Th7f7zVNBzeVBS6VjixMKqgHdlIl0PwgOjVU=,tag:+oitKaGZtloLRbjvwbmg1g==,type:str]
  URI: ENC[AES256_GCM,data:92KcwIjG81EGb44hzKrv4mvCUUxM1RlqTCWbOmqrSmEQermiqvzFGyPsGijCVZaqH2yREJMxQG45QEjq6Yv11v2h6f/bsGyvH2gMFd7/2g==,iv:4gJKQHT2+zqKUwPuP6is3oVTE9GvXoX5vnk/Wz5WHRE=,tag:1oNuk+zFcXAFMwft+djfOQ==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:J4QK3re8,iv:kcdyFg3jKXS8T15C6zsQTBipTQXgr3/7KQ2FxLxktoU=,tag:HdVHf2pdVqv7VaNudFCAUw==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:VeprBdVC39aUxiSST83GbIulQ08yANBxscnJnPUgfw/ccsSB2wjWqg==,iv:fDpwIhQ/hn6Eit3buDc2u3wiPYGHfjh6myeSC+mNzho=,tag:x2KvSEe3ptFadEPYqD4FeQ==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:baAyYW3V,iv:dByFG24IS1MstekUVzjGc9U3f3yv77+EwGOI33NiyQI=,tag:+GO6I+KGOsC4NEqTr1jivg==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:5hrR5Pk8lqA=,iv:0gxtmpxy3wd9mnCsjg7JA9nHH0P1wtffo3tjS3V5Eb4=,tag:qx6c2WRjVP4pDujj0J750w==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:BmH3kS+YvKc=,iv:1q6gG+muw88pWBWoMSRAW+5+qNqCCZYf5tL6VKtGkZU=,tag:Cc3k4LN3Npuplh45QhY9Jg==,type:str]
sops:
  age:
    - recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTnZaWDRTMHUzQUp1YmZj
        Vlo3dFBsaDN0U1Z5ektRNEtmMXJIOEpDUkJZCnJQMHRteEhkcTVPdGtJdjF6cWN1
        a3FVd3BVOTZ4SUxnbHdma3l6TGw4cm8KLS0tIG9aamZNY0hZdjkrbEdZQjVFbHAx
        RStDeU1xd3c2QkRPdlYxaC9LN0Zad00KQzdGE+ONxLBlnbdppqbrCmFBhusO/ION
        7pHdoP8TQ9IKm+neOGkpZY38vf0acA6DyGUv6qIZOYmcyxiFpbn5nA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-28T21:10:43Z"
  mac: ENC[AES256_GCM,data:SuGzHyjhVm1CZu9ibuPSVhrP+CrQimBKEdRji13jMVpTo/1EVZUBaza1Nma5HHBd9jVw4+tGutfqV7e4lZ5u4o8pkuMQqe73IuoaGD9oa8y635FuO91lX/8N1Xj9HoCPtaZDQmg4R57FE47Juzw9MX5/wMbB0c4ZHU2g9S/fnn4=,iv:xIN8ODVNmHZme09S7yTzC7p7NjM7w8SP+WosKZiYfLU=,tag:1YNnIjeZDn4RiH/aKI+ulg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
