apiVersion: v1
kind: Secret
metadata:
    name: bazarr-secret
    namespace: media
type: Opaque
stringData:
    POSTGRES_HOST: ENC[AES256_GCM,data:nckmnyKBmVr3JzssJ2SdeDmmiApq2a/NCDWDhK5MbqXCHdeYgQkmwg==,iv:L+EQkNIhwWr5DJSC043ZYLZCWgyez6rulD8sa4TpJl8=,tag:na715XygUmxxydii/tF5mw==,type:str]
    POSTGRES_PORT: ENC[AES256_GCM,data:pryhgQ==,iv:iwyq+iaMJclKnzujpgRjzRb4eXuNuhHK5FF9zx1AQKg=,tag:zh94umI56qZU9Z3Nwp5hpw==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:wHO+Rijh,iv:pIM4t5vUhKMfs6/wCE2JSAXN8w4MwHGFc7vuNBLb6q8=,tag:gOzcOmFBghuSpkgZcM6YDQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:HnKCuf1H,iv:DPfeDAa3036rkpna9KPBhMswy4Av7EsbA2falIpYt94=,tag:FLhyA2MA0htxfJQXEoXmfA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:uM3zusLjob4=,iv:RQYHhLh7FjcrgVCMypIv6f8eQ7i44qlQqgdL+AwY9ok=,tag:h6JwlwF5snbdVB5y5TtraQ==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:jCR7ti5E,iv:hCH+egP7Xq9x/LJFzMbQTgTlBC0LNqNss9lxnlbRbSY=,tag:YgfXBhwO3TGioyQmhkJfEg==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:bzJWP9eNGBk/JQ3ulIElSQ51yB0DgryfOIblwySA+bHVV6/QxT5B+Q==,iv:6wws07ikybn0fTPBYZ8jlS7L/e6mjXj7D+pxMQS7bvg=,tag:MINXN894F4Mbg46blRyAiQ==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:xbdwJ9zL,iv:xXNttyvPTO3X1WlBd8q1mG2LtSXwEN6Jpg8qcK8BGn4=,tag:YzfsZ+y7+jiPZivOf/0k9A==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:zwB0CIq/dI4=,iv:JUtUT3ALsXLp1V27baxWpt3hx8Ib2X27yD5kSTdhL4A=,tag:YNpR4cNKZprmjpx8yC+C5g==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:SDRovI7vN94=,iv:Arr5Q3SReBzTFq05m0epOcp+xzsG3PXKx40ckjRk5sI=,tag:NED12hT97EDJomQr7ilUPA==,type:str]
sops:
    age:
        - recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2WFdYWWZzYTVTY0hkcDRm
            dTZQOVZ5eFZTK0NxVERVSG9oL1NyT05ZL1JzCm1ZV2tmeUNsQVZydWtvVkZodmVV
            cTlXRTlieTE0em85YlBYcGN0STVxMlEKLS0tIGlSbnVYVHE5RURUbisxVDdlV3ZQ
            RjRYUTVWS2ZSK1pENzFvOS9WTFhBUjgKupk0EeHRErfpG8lrYkksr9OmgOTalXJb
            b966I64pWQdG7Urb4pNIOyHpJMBe6DX1vvqQ8aszXNi8UKV6ktoJfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-08T21:10:08Z"
    mac: ENC[AES256_GCM,data:hFWDBNVdl4Zsm/CknYFoBlvHin3Siv+4smteO7FNsWe7hCpvWb8RseXxrW/KyTwq9T8sSkxfDO9ngebJ1J4+feP9O5BrB8RlYAxXxd7APENces6Ui6AKIDF6SajXlp5ysUXcY8h+wOCZ8Vh6XbKRc9iLv5GW5Jl0UYPITPopTq0=,iv:i6k5J8l6TpzAgMUOJ5Z89DT/MuLYA+2qbeOIFVU4k6k=,tag:qmYqjZDxz6tXFD0pFYbgJg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
