---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
  - secret.sops.yaml
  - httproute.yaml
configMapGenerator:
  - name: p2pool-dashboard
    files:
      - index.html=./resources/index.html
generatorOptions:
  disableNameSuffixHash: true
