---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
  - secret.sops.yaml
  - httproute.yaml
configMapGenerator:
  - name: p2pool-dashboard
    files:
      - index.html=./resources/index.html
    options:
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
  - name: p2pool-nginx-config
    files:
      - nginx.conf=./resources/nginx.conf
generatorOptions:
  disableNameSuffixHash: true
