apiVersion: v1
kind: Secret
metadata:
    name: p2pool-wallet
stringData:
    address: ENC[AES256_GCM,data:Vb4PIQ5eN8PprK2p3PRP+21512hjU+bHB3HANgW48UR8tD1/wLKFSClHy19p/Tg5aOdGtZLGgee2MtevQqgloBKlyh6pnMkz6rmcwtu2gcQdqORwprU9+0V8RNwlJvM=,iv:il+5GF6FYSGAbHApPuVuZT954qMFoqZkcV0JUC3m1Vc=,tag:JDNhrQzNe/KDWiOucGfn7w==,type:str]
sops:
    age:
        - recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ZXlUU2lISFhOSFNOdjJ4
            UUlJampHL3dDd3RPQTdwbmpzZ1VzTG5IZVFJCkI1NC8wMnYzRmdKTzVNdGUvbWlV
            ZDhIZFcrMVd4TEhqbHpiU3N0bjRXdlEKLS0tIHA0SS9TYm9PSUVHWE9nSUlOOHYv
            QTBpVFlZSUU2OTZpTmxnb1hwYnh6UEEKa2HuU2qq3zVF95PnA6D2ve8A65EbRoOE
            hGY950vMGpleoL5DhBu/TbgTXWhlwMhAsEmyRh88pf5SOEr6+oQFGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-20T11:58:15Z"
    mac: ENC[AES256_GCM,data:ISIfIFwhBxfM6a3W32cBsLYrRM6FgwAGOUWDvmWIGPPMzvF2qXhLroIzFn5hm0ayw924DQ76kiON/XPs8JpV2Tt8AUamDgsGWelihEPdSmX2gmgSDnx3rH+dqGUxzGQZe6otL3/cfcyfC5p4Z83CYZDm33zhTUwnSzVveX/i38A=,iv:DWLPVKDqqJFq6F62qS7cMHoWUAY8uif1ao4dN/v0wPc=,tag:b+4FLkGM6Nl4QGGVSFbQaQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
