---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: monerod
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 1h
  values:
    controllers:
      monerod:
        containers:
          app:
            image:
              repository: ghcr.io/sethforprivacy/simple-monerod
              tag: latest@sha256:83a4a02065429d99ef30570534dda6358faa03df01d5ebb8cd8f900de79a5c77
            args:
              - "--data-dir=/home/monero/.bitmonero"
              - "--log-file=/var/log/monero/monerod.log"
              - "--rpc-restricted-bind-ip=0.0.0.0"
              - "--rpc-restricted-bind-port=18089"
              - "--no-igd"
              - "--fast-block-sync=1"
              - "--zmq-pub=tcp://0.0.0.0:18083"
              - "--enforce-dns-checkpointing"
              - "--enable-dns-blocklist"
              - "--out-peers=32"
              - "--in-peers=64"
              - "--add-priority-node=p2pmd.xmrvsbeast.com:18080"
              - "--add-priority-node=nodes.hashvault.pro:18080"
              - "--prune-blockchain"
              - "--sync-pruned-blocks"
            ports:
              - name: p2p
                containerPort: 18080
              - name: rpc
                containerPort: 18089
              - name: zmq
                containerPort: 18083
            resources:
              requests:
                cpu: 200m
                memory: 1Gi
              limits:
                cpu: 1
                memory: 4Gi
    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      monerod:
        type: ClusterIP
        ports:
          p2p:
            port: 18080
            targetPort: p2p
          rpc:
            port: 18089
            targetPort: rpc
          zmq:
            port: 18083
            targetPort: zmq
    persistence:
      data:
        type: persistentVolumeClaim
        storageClass: ceph-block
        accessMode: ReadWriteOnce
        size: 150Gi
        retain: true
        globalMounts:
          - path: /home/monero/.bitmonero
      logs:
        type: emptyDir
        globalMounts:
          - path: /var/log/monero
