---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: external-scrutiny
  labels:
    kubernetes.io/service-name: external-scrutiny
addressType: IPv4
endpoints:
  - addresses:
      - ${TRUENAS_IP}
ports:
  - port: 31054
    name: http
    protocol: TCP
