---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: external-scrutiny
  labels:
    kubernetes.io/service-name: external-scrutiny
addressType: IPv4
endpoints:
  - addresses:
      - ${TRUENAS_IP}
ports:
  - port: 31054
    name: http
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: external-scrutiny
spec:
  ports:
    - port: 80
      targetPort: 31054
      name: http
  clusterIP: None
  type: ClusterIP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: external-service-httproute-scrutiny
spec:
  parentRefs:
    - name: envoy-internal
      namespace: network

  hostnames:
    - scrutiny.${SECRET_DOMAIN}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: external-scrutiny
          port: 80
