---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: internal-truenas
  labels:
    kubernetes.io/service-name: internal-truenas
addressType: IPv4
endpoints:
  - addresses:
      - ${TRUENAS_IP}
ports:
  - port: 443
    name: https
    protocol: TCP
  - port: 80
    name: http
    protocol: TCP

