---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
data:
  TIMEZONE: "Europe/Brussels"
  OPNSENSE_IP: 192.168.0.1
  K8S_GATEWAY_IP: 192.168.0.3
  ENVOY_INTERNAL_IP: 192.168.0.4
  ENVOY_EXTERNAL_IP: 192.168.0.6
  ENVOY_INTERNAL_TLS_IP: 192.168.0.7
  CLUSTER_NODE_1_IP: 192.168.0.11
  CLUSTER_NODE_2_IP: 192.168.0.12
  CLUSTER_NODE_3_IP: 192.168.0.13
  TRUENAS_IP: 192.168.0.27
  IPMI_IP: 192.168.0.45
