apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:Cm8ajV0NJfoLSQL4bjc=,iv:KVhpP+u4EC4BsLOMnbfVJBH8Y22Wqvr6KkCvpYPl0jc=,tag:gFWLCvFd3Uuf6PljkifTAA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:zfX+5QBTitDySDneaeY5GbGV2IE=,iv:hVOrHg0gpLfDAg5tnK0mP/0+uq4NmRegESSJerVARxo=,tag:FbTo3EZ8v6rW9V5NMvuqRg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:YZpwF+A/HicPnoTni01VxaNcaCTH2hVUwQTlVtl5/q8OjOVW,iv:7lUPIkKqALU//fJiRMstJywE8owFCDY8WppYmF/9tII=,tag:MJFELD3g+f+TPsSRzo1Fyw==,type:str]
    SECRET_R2_HOST: ENC[AES256_GCM,data:UV6DLto3bI46ZSYYdraHHYcexU2sTeG3Q6ERAi5uLBUdehs4TVySuVpOR+nEvgh+alfNswtzYewJRCHltMEz5v0=,iv:yBDztVgfp+prxKSsejiQc4RVhffF898nXI7llMsPfio=,tag:k9SXtSnqUAK2UxmQbhR1Nw==,type:str]
    #ENC[AES256_GCM,data:ATO14DaX,iv:O0bedo9/F6wfkZJyuA3v08GikQue4jAIKINRL373aLc=,tag:OEqy1osoxxOZjw6z43QxMQ==,type:comment]
    PROWLARR_API_KEY: ENC[AES256_GCM,data:Tc4QeODIBwo1vXP6piMJbokmLQkmL3mYuAv+5glgE0k=,iv:943lJulBQ5A7BmYlO2lIrxcKVW4+5oIoRElP+HeQ3kY=,tag:fiVL5QNNpcOga3K2JVTLBw==,type:str]
    RADARR_API_KEY: ENC[AES256_GCM,data:+c/5fgBMjv3IPYIBhBMI8/wa89r+LJWvecN5TDjpsKk=,iv:IlRjawRiddHUZKUPHaZ06plz1dlUc0xyubFxeP4Ql5Q=,tag:NrnNlohmTNsav+Cwi4mpeQ==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:fh3IdlFimeoDpnMfUgPkn/K4F0usCou0N9OGlMHMjB0=,iv:nJQ7RylzyIuONmuOJDNSox4iC4Ea15YRk6sA7r/xWoA=,tag:DhuI0IAlQZVB8YIIOf7HVg==,type:str]
    QBITTORRENT_USER: ENC[AES256_GCM,data:qYAbnAyohYkZ,iv:Ojpj1LYl5T3MwXxuaY+NqrcVj7rLQWPOZPmvtFHxQ30=,tag:Kv0uB5nWgw4X3Dgw4f3zUQ==,type:str]
    QBITTORRENT_PWD: ENC[AES256_GCM,data:O5xloyDQYHw=,iv:8aJB68LqEBGBke0TViOaG4oU0jzv5X93so27+hI+HCA=,tag:8JAPUibieAaTlMIFNj6msg==,type:str]
    JELLYSEERR_API_KEY: ENC[AES256_GCM,data:QyRFw5d4RCoyCYa2eP+X69a3km5riKm0wvv/fWdgxDYDPspCxVd4yE9KfwgBVG76UEwLFR5lGcQiW5G+xU/U4+izmVU=,iv:Ttc+LafseP8sUK95ksKTt4b1tTezHPlCwFsw75PB/d0=,tag:jLhd9u0oViBB1o5uw0xq3Q==,type:str]
sops:
    age:
        - recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWU3dGb2RCKzZmNXpnaE4v
            ZzR0VkpiRlVxWTMyUUxRakxDZ1VsL2c0R2l3CmkvMG52ZGJrakVmcWlMSnhLQ3hO
            TDNXdlMxaGlrQW9jUHI0RTJzbXdkblEKLS0tIEQrdy9hWkl4NU9zK0RIa1FYeWlQ
            RHpURWxuc3FMa2t4TmRrdHZ6NzdBZEEKrQysJKUFF1PD+hNo9lX0RPwlckD4+343
            +OihoUp5eXHyh7fBnoyyesSdh9rsuqUuJwaSM5UnvvMWKKMnJshsuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-13T22:48:00Z"
    mac: ENC[AES256_GCM,data:erHmDhuG825/G7B3fDcRAcXTDHiGxTK2tnSeEJjdiKlytuw+fKg0VPsgPfPCJV3ZHI+7jD7hpkQJKoDXPpP5zu86VhvxUX+wm7H+Iqipeh7BVd4fpvFbdHqSjpqYvZEESN+U0envNOZKDHkTv9DPKHh0Z6YPhE4Obt9C5LlThjU=,iv:Tq7F7umKs5zTuaNBj/rrRXhbdN0NHnv3X1zrUHvCUvQ=,tag:b1MGdvt852FqMI1WagF6SQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
