apiVersion: v1
kind: Secret
metadata:
    name: volsync-maintenance-secret
type: Opaque
stringData:
    KOPIA_FS_PATH: ENC[AES256_GCM,data:8T3HVVJSOZgJxAc=,iv:0mZsWx1I/+FPvpuGkzvHuKjXsWvQxkjuti+6ZMjceUA=,tag:EZY02bG9pe2M2RqjrvkiqQ==,type:str]
    KOPIA_PASSWORD: ENC[AES256_GCM,data:SzHKmuAp3Xw=,iv:y5SfzkhN55iOAbnWhnC4fhOJLM0zKA5h6gJxcYcTYaI=,tag:UaIWcRdKPdC2tdC/hHuEiw==,type:str]
    KOPIA_REPOSITORY: ENC[AES256_GCM,data:BxLsXQt44niDkd3HZwiXBYb8HxyKar04,iv:n+IIpXeR94weOYZP3sOUwRIugi/Gs4jpmDjALIxsqhk=,tag:6hzq8B8HI3c8PgJHdzO73A==,type:str]
sops:
    age:
        - recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCcHRCemJiTHdyZWFxODVI
            b2ZpeEFINko4N2FOd3loQkNWS2VzVDNDTEE0CjlVOTlsaFlXS2N6VlVGMHdFS2pF
            a0dJbDRqalJGQm9QelJrQjI3eS9TYjAKLS0tIFd6RkFNejBrekJXQjAreTMzYUl6
            R0JCNTJybk9yQWt3SFo3NXg0cDZ1aFEKewD3K2im66SLFhVhUBbIj69dvrsWvphZ
            c9ZORmLdDON3Argdorql1MfEGIV7y4E9HF62VVeJvzgsv156kxxP1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-21T19:40:32Z"
    mac: ENC[AES256_GCM,data:N0d0Qy7OfA+aAyZuexUNCdXsPA2PkEnWpBYq6quGSaJsMaTHqoMrrVLZChSCueajNe0At1WtcuDHrfDP3c987c4t/NrTFv4jv7mmSyVJele+yya4vJiaRhj3N1AdNKyJjQ3PfTfA8pDt3K7OIpXwAPqCXl0Hqi5gM2525QoNx2I=,iv:3wewUWLuuqAlkpdId+e1L9JT3HnKmburedMMskVTBS0=,tag:PLpVMuWis6vu6GwxSz74VQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
