---
originRequest:
  originServerName: external.${SECRET_DOMAIN}

ingress:
  - hostname: ${SECRET_DOMAIN}
    service: &svc https://envoy-external.network.svc.cluster.local:443
  - hostname: "*.${SECRET_DOMAIN}"
    service: *svc
  - service: http_status:404
