---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: toolhive-operator-crds
  namespace: ai
spec:
  chartRef:
    kind: OCIRepository
    name: toolhive-operator-crds
  interval: 1h
