---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app karakeep
  namespace: flux-system
spec:
  interval: 30m
  path: ./kubernetes/apps/default/karakeep
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_RCLONE_SECRET: karakeep
