---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./dcgm-exporter/ks.yaml
  - ./nut-exporter/ks.yaml
  - ./prowlarr-exporter/ks.yaml
  - ./qbittorrent-exporter/ks.yaml
  - ./radarr-exporter/ks.yaml
  - ./smartctl-exporter/ks.yaml
  - ./sonarr-exporter/ks.yaml
  - ./speedtest-exporter/ks.yaml
