---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kepler-operator
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: kepler-operator
  values:
    namespace: &namespace observability
    operator:
      deploymentNamespace: *namespace
    metrics:
      serviceMonitor:
        enabled: true
        labels:
          prometheus: kube-prometheus-stack
