---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kepler
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: kepler
  values:
    fullnameOverride: kepler
    serviceMonitor:
      enabled: true
      interval: 10s
      scrapeTimeout: 15s
      labels:
        prometheus: kube-prometheus-stack
    tolerations:
      - operator: Exists
    daemonset:
      resources:
        requests:
          cpu: 160m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 128Mi
