apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg-secret
  labels:
    cnpg.io/reload: "true"
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:q6lwTwPQeIWC,iv:gkCujHmNEVss6dD2mmO9eCJcd1/3JiJwbXQMQgltCHY=,tag:caaJa14QRTotnfb9SyCj/A==,type:str]
  password: ENC[AES256_GCM,data:kH3xkxmKtao=,iv:PnvgmbGjqp5jIxMClnPPTmg/BKDxEWS8WeYE2L8b0OA=,tag:QKjtkAyee6V+DPw7I/9ndA==,type:str]
  aws-access-key-id: ENC[AES256_GCM,data:R/cW0ptIKVZ/xfq9Wr5MOyx8Tw05uu+avgFJrVK0F2Nt+SBdHiKV5GPIcDy0Qzy6fIHXSm+PYLnk5FsPUhmls5SoLAIqQ9vJafU4u7ETqj8AuGjm4Bv9DL3cM1PzirZeMxPTNTOs65Fyh5rYnCVngGSaoxCaTQjrY33i4mwdrLk4SFlVUlPkVUdjxTKJHOhwQaokwzpISw==,iv:fR8TUkmwSDbg8MMIRf2PzUW1Fhb6i7mLU3eKSjZHiMo=,tag:ewd57JvK8F6MdPAAt4CJ7A==,type:str]
  aws-secret-access-key: ENC[AES256_GCM,data:4P+kzqm213Fc49kruSXqmOZKLeX073uVYl8FWCkSGwkmMzDh/tq0flF9ZNhuWzxeqfOaaCWdHRIuE8Ls80Wsv3AYQ0fTRYYXjV4mGUYgPt0Wu3mPBAGwSdkrrN+4NEmsvpauvPFF7fFLni9hH6E02k6td6VT8Af7mcO6lIGVUdqaXcQQ+eVJqo1pOIMOn2WL6j+czp+dUrkbA4lMP5gFPo57tSCiJDpuMd7FK0rJkl6yyImxxfE69kzbPJHAJKs5xGm+,iv:G04ST5cZ6IKzSyQtOqrQHbW6xfUNatOY1wddzMYI1s0=,tag:we3tv7s5APJrqiPgqhor0g==,type:str]
sops:
  age:
    - recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZlR3NjVuYWZwMzR5MWlr
        N003Sms2UTN5aVFsdU1LanV6TytFb29nWkNJCnkxRllEUURNZHF2b2wvVy8rUURZ
        T2RSYWx1N1ZiVjZhbkdyK3JPZjV0RWcKLS0tIDJqL3hrVXBxZ1Y4WUV2eGRyM1lj
        ejZ6TzRjQW12YmdGYUcxOUtVT2ZQQXMKdtlavpGUObBWV6jfL0LDnDCUTdMdud1J
        TZtpvG8aSvbcblvEkohqHQddSGwdud1hdmAKf8Vaa2lgq71SXr8Hyw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-25T17:04:43Z"
  mac: ENC[AES256_GCM,data:B/hvWiC4NYA6Nf9fBvyasSIxVPARqRxnF0nByX7yZfmx/CdapOwS8T6w05COUzvSDsrYD/t9nYinfHkPjK7SALVipBNqdO1YwLXpFOyGEPpl2zGPOeUBtyFiG70Je/flqEtXGuI3aB6DxuEKZ1GZlW05ytUsKzWdNKv6m/xhjx8=,iv:0DYZocUj4s3Axvdou+4ubzlosyIDuHBiDWwBb3aDvgg=,tag:e/PfqJeJQceu/amJW1PHcQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
