apiVersion: v1
kind: Secret
metadata:
    name: kopia-secret
type: Opaque
stringData:
    KOPIA_FS_PATH: ENC[AES256_GCM,data:AqUHnrujaX0Qldo=,iv:A43wSbvkkwGWHTLE19u//SFO6F3GBTWtYJTLSyIgleo=,tag:Yx+gGZ1judHOXOB9QEK93g==,type:str]
    KOPIA_PASSWORD: ENC[AES256_GCM,data:SzHKmuAp3Xw=,iv:y5SfzkhN55iOAbnWhnC4fhOJLM0zKA5h6gJxcYcTYaI=,tag:UaIWcRdKPdC2tdC/hHuEiw==,type:str]
    KOPIA_REPOSITORY: ENC[AES256_GCM,data:31oCRqX3M1ugfF+3ptN9/iFbt36FAx5c,iv:gWvQ23ThXfsHmg21nbEmXS5bWJrygJFDHVrO6iMMuiQ=,tag:7I5L9kgZWEdA/fDpMgGTag==,type:str]
sops:
    age:
        - recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCcHRCemJiTHdyZWFxODVI
            b2ZpeEFINko4N2FOd3loQkNWS2VzVDNDTEE0CjlVOTlsaFlXS2N6VlVGMHdFS2pF
            a0dJbDRqalJGQm9QelJrQjI3eS9TYjAKLS0tIFd6RkFNejBrekJXQjAreTMzYUl6
            R0JCNTJybk9yQWt3SFo3NXg0cDZ1aFEKewD3K2im66SLFhVhUBbIj69dvrsWvphZ
            c9ZORmLdDON3Argdorql1MfEGIV7y4E9HF62VVeJvzgsv156kxxP1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-21T21:03:40Z"
    mac: ENC[AES256_GCM,data:OfFwYhs8iw5XXZXeVYwIPEYqyGMYUpoDsXB2N4NLEYoNQBGVB1GMCy1Xdud+S8yffNVgtks1qFK5L3H1A9W0EXEJYOmIE1sHDOHt+ZU6SLXOhPcivUijRKfCPobBCqnRTGN7iRYvy2BIa6krNXgmw0yhOrCXasv5EhKG4qEH5Cw=,iv:UG5zQtoP9TcmaXPYIBPxV+JCer2/2t6aSm3mwT6ML7M=,tag:qoJj12deefO5xZDOzFiM9g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
