apiVersion: v1
kind: Secret
metadata:
    name: kopia-secret
type: Opaque
stringData:
    KOPIA_PASSWORD: ENC[AES256_GCM,data:SzHKmuAp3Xw=,iv:y5SfzkhN55iOAbnWhnC4fhOJLM0zKA5h6gJxcYcTYaI=,tag:UaIWcRdKPdC2tdC/hHuEiw==,type:str]
sops:
    age:
        - recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCcHRCemJiTHdyZWFxODVI
            b2ZpeEFINko4N2FOd3loQkNWS2VzVDNDTEE0CjlVOTlsaFlXS2N6VlVGMHdFS2pF
            a0dJbDRqalJGQm9QelJrQjI3eS9TYjAKLS0tIFd6RkFNejBrekJXQjAreTMzYUl6
            R0JCNTJybk9yQWt3SFo3NXg0cDZ1aFEKewD3K2im66SLFhVhUBbIj69dvrsWvphZ
            c9ZORmLdDON3Argdorql1MfEGIV7y4E9HF62VVeJvzgsv156kxxP1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-21T19:41:26Z"
    mac: ENC[AES256_GCM,data:6AU6IXJzK8scGdfwqaXVeWbIB6pdORNEy/AAUDn+O0zpx12Z7a+MWide9g/0pYnhJTgKGwMHydwbmRdJXFhP2Ik4lkea7BTleBUHF+CYbs6AQz/vtJJrmRn/meIzUC5PlfYz9EUzr36Hha1aCstwIFCuDUMgfw4Kf2f8nUVqftc=,iv:9Ga6gYfGUAknG/ieOjMSGCrYDFdA+P3NlMOgc4PbqSI=,tag:EXtn5zHW3Y3S2o1Diqne6Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
