apiVersion: v1
kind: Secret
metadata:
  name: bazarr-exporter-secret
  namespace: observability
type: Opaque
stringData:
  BAZARR_API_KEY: ENC[AES256_GCM,data:xAjsjdsoy3OxbEjFBWFGIdNO8eofbsYnjBZZv+7nlBU=,iv:MifverDALuatHZiU9hhnKNiU7/13STlD6hZomcxOg7s=,tag:nzQo/NKReeLMnjQsIWpd4w==,type:str]
sops:
  age:
    - recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2anNSS2RFMkhueDJhczhX
        NlUvTVBQOEROdWpsZHVCR1JVTFVxY3dRN0dRCnZyUUh5TTkzL0M4VFo0VE5GOGdU
        SWljMGEvVzRtQ3NCTXQ1eFJZRFBYOVUKLS0tIEQyaTBNcm1PVmJpQ0l5WVRNbVQ1
        TzBVVFl1S3RPZitRczhOTENDVXhJU2cKAU7yUViSZ+wWGLeievSEZLYddBKV7bNQ
        otbKShr1tIdnJDa8SV9dVVCHUmv4jWuUNd10RByzL2YvobPqF8RGQw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-12T23:00:19Z"
  mac: ENC[AES256_GCM,data:ecdF8nF9Qb4BrZJKYkU4uLKSm/yI3Q+HOxObN9Qw2dDMVwh76TfRv0YM023mJxK6ohSw6F4GqWwN5P5h1J9NOp38pGErZTWWZH26rzeTRUsEExmxVCMvL3YvbNQ+byvwVYFM/LclaBNhvB/zO9M2xXs/kdFDuCi/4CnNcX1V8tg=,iv:DPTHx3KMsvHVZ6c2RuFTkF9MwX9hKE12xfDQGvtLMck=,tag:uwR9dUSYyljtJ/kLZemYyg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
