---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: xmrig
  labels:
    app.kubernetes.io/name: xmrig
    app.kubernetes.io/component: autoscaler
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: xmrig
  updatePolicy:
    updateMode: Auto
  resourcePolicy:
    containerPolicies:
    - containerName: app
      minAllowed:
        cpu: 1
      maxAllowed:
        cpu: 8
      controlledResources: ["cpu"]
      controlledValues: RequestsAndLimits
