apiVersion: v1
kind: Secret
metadata:
  name: cnpg-s3-secret
type: Opaque
stringData:
  aws-access-key-id: ENC[AES256_GCM,data:WuesTEHKoA0SDWXUkGIHaiwC8XY=,iv:NZkRwK2JtuoCV7RXpViqIyRAfzUX5sprRUbJrfpZt/w=,tag:/bw9KnymxP8SirMXIiRFvg==,type:str]
  aws-secret-access-key: ENC[AES256_GCM,data:sC+tALeLwrR99vH5YgfiFWK6ZMZhXMhh7FiDq0sYp4Z6zAuf17wS,iv:+jqhvC5DxXn0xQV44H4R+6RTZ/nllXq7Q7hLILCO7d0=,tag:gSdEBrRAUHY74eKkVgy0pg==,type:str]
sops:
  age:
    - recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvRm96TW56aG9Jcllpa01Y
        Tkcyc2pUMHBoeVdXRVFCMkx0Um9EZVpqSW1vCnR0MUJJVWo5VWp4Y2RWQnNzaWZm
        NlVkQURKb2hYSkNiK3NNRVN0Z1ZPckUKLS0tIEVURFEySmt2OUxpb1pvUGc3Rlcx
        d214K0dIT1pwYWtwZWVtS01oUWNMeFUKke+376h517SjAiECLi16tmJZWQD7lZRB
        XCY1w6aVfHQpjnOx+nbT4jMS86GgX8oGsvliiTsyXS/Jq/VtyBJp/w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-21T12:11:27Z"
  mac: ENC[AES256_GCM,data:nDkb7HdYdPHylOktZnlFOWj4b3hZCUtqfe8z61/QdWeAVmH6e1hltmeFgsXZzCNlG2tevhypX39VbR9f3LH+SGeE7a7tIZCVJVWbZoGyJ0cXvA97M2xO7HCW+DDI7tocVbINkgRak1Kc6WZqyASuc5gPIqU18TV/sE5o8zViwcM=,iv:j8Mn8/CGVyDtcTScFGxU11hL6f4b9vuICvpRzyf45f0=,tag:nCoSfODXYUAQwht9/6C4ew==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
