apiVersion: v1
kind: Secret
metadata:
  # rook-ceph expects this name
  name: rook-ceph-dashboard-password
type: Opaque
stringData:
  ROOK_DASHBOARD_PASSWORD: ENC[AES256_GCM,data:8JWi/hx8Bq4=,iv:nQ2F5rxFWia9X0m8uIB8pLVfpeT9yHgKb+wafyN5qoE=,tag:s2XqvaMLaGxvJfXMbRPA9A==,type:str]
sops:
  age:
    - recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSlpNbWZVbEgvK2Q4eVRV
        WWpueHg2bmNwUW5CZHJsVmdBbDJZNkhRN1FzCi9qSHRGZEQxRVMxRm5pdHBFZjQy
        bWRNWkF2N296elFHSkUvaE96dDJtYnMKLS0tIGY0NEVOempCRWxBaFg4SGViRVpT
        cVN3eHhoaEpYTmg3bEcrNDNGdklqaEkKkDq6X7LZwBIOlJSJfku76/8wyFialBeW
        y4aH0If+Q112z7T7mkXFEqvxqOrGHmrv3XpzywRU8NTynLJ0R9dZUw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-14T11:24:47Z"
  mac: ENC[AES256_GCM,data:Luzv6oVZJp71MVfe1ObXq++e5b7tHOKGCdRqnh9cq3aR8twhfplUMTOW441ewpass+N63cKBKf4u7dRHUm/j9eR0pPKbKSDKbXX+KL+kxbh9m7XAaGOFIwCVqKkH19sleqQAhzgWRRuiGcR9MB6EQ2FKD72DHKA3WJ3SQjw2Dyg=,iv:FOuT0Rk81ZHCPLkG6i9mjuqLpTyjU1qrw87zjDRaSqg=,tag:Un1OswpHOUCvum+lWx62GQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
