---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: internal-ntopg
  labels:
    kubernetes.io/service-name: internal-ntopg
addressType: IPv4
endpoints:
  - addresses:
      - 192.168.0.1
ports:
  - port: 3000
    name: http
    protocol: TCP

