---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: ipmi-backend
  namespace: network
spec:
  addresses:
    - value: 192.168.0.45
  port:
    number: 443
  tls:
    insecureSkipVerify: true
