---
# Secret containing the self-signed CA certificate from American Megatrends IPMI
# This allows Envoy to trust the self-signed certificate while still validating it
apiVersion: v1
kind: Secret # but actually public information
metadata:
  name: ipmi-ca-certificate
  namespace: network
type: Opaque
stringData:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIEgDCCAzigAwIBAgIBATANBgkqhkiG9w0BAQsFADCBsDELMAkGA1UEBhMCVVMx
    KTAnBgNVBAoTIEFtZXJpY2FuIE1lZ2F0cmVuZHMgSW5jb3Jwb3JhdGVkMRswGQYD
    VQQLExJTZXJ2aWNlIFByb2Nlc3NvcnMxETAPBgNVBAcTCE5vcmNyb3NzMRAwDgYD
    VQQIEwdHZW9yZ2lhMRQwEgYDVQQDEwt3d3cuYW1pLmNvbTEeMBwGCSqGSIb3DQEJ
    ARYPc3VwcG9ydEBhbWkuY29tMB4XDTE4MDQyMzE3MjUyM1oXDTM3MDYyMjE3MjUy
    M1owgbAxCzAJBgNVBAYTAlVTMSkwJwYDVQQKEyBBbWVyaWNhbiBNZWdhdHJlbmRz
    IEluY29ycG9yYXRlZDEbMBkGA1UECxMSU2VydmljZSBQcm9jZXNzb3JzMREwDwYD
    VQQHEwhOb3Jjcm9zczEQMA4GA1UECBMHR2VvcmdpYTEUMBIGA1UEAxMLd3d3LmFt
    aS5jb20xHjAcBgkqhkiG9w0BCQEWD3N1cHBvcnRAYW1pLmNvbTCCAVIwDQYJKoZI
    hvcNAQEBBQADggE/ADCCAToCggExAOCRNUnY7win6Y9dRrksfQVEzx/1UJCTbPfc
    r5a1KehMBDeTcqFaKuJaxK5r10lafYM5otd6lESAOm2WACj5Ek7nQXckjFmn3WBb
    t6btsspAWLffVVl7dRUqkUAGwGw8p2R8Dqmza7G1bUqcmV9umLNXdoz+MoOVz55v
    0XRdnGlRXL6dTFXWDu902E458VbE/MPvAaEuu0Z/au+ma9pYiYmiMivESjooJ/hK
    A3uM7dEoWZmbC10MoQjo1rP298fjEAnU1hRMChL8TmLFCAyQuF9bNtao/eS273Th
    Gq/1ztNl7s6r9YGMjdQNz+XJeKAEP9w0cNz8lwF2Q8XDmfYK/GWZg4TiloU5em/e
    nbnmppj5eoOdt7W5DXoRJg4G7QW7G+2odyDUQ1gvj9V83vkPGbsCAwEAAaNDMEEw
    DwYDVR0TAQH/BAUwAwEB/zAPBgNVHQ8BAf8EBQMDBwYAMB0GA1UdDgQWBBT16oSM
    ijHaI5MwnpZ4sYxhqrKUGDANBgkqhkiG9w0BAQsFAAOCATEAlWEruVxO/tHeLNWw
    a+nyumOu3zEUyi6ptNVUY2ZASO/zq25ZN7OB8In2vyYNDXBV64P0rg5Rmqcg2RPI
    4cRAY44LdDnbVQesopyWCNY3ZMzcfc+9cLv+8HxQ3Mf2ArCPYkoneaCzU7VqfZaH
    OZEvIPgTbBtceknFcQTzfyHm3R6TTeCTEwaj34FEzr8l3hvn/db2khDru5dGJ5LU
    jSf4liFkBSk7JePuTEzYh4ZcXvOhjjxqrCMhI+8QureWK3iqz7FARMjKeCaNpiGP
    QmE6fvRvDCOPyBO9MoiSRCqBg7u9kHnY5PunMkSrx/ueE3py5NM5amEeFqDJH4+u
    qj8CTVQQrUjfDVXRfOF0Bt+4clBuNqX+o4IBbsHJp2KRp0XIowXKXYPO2+DVKkVT
    x134Qw==
    -----END CERTIFICATE-----
