---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: internal-ipmi
  labels:
    kubernetes.io/service-name: internal-ipmi
addressType: IPv4
endpoints:
  - addresses:
      - ${IPMI_IP}
ports:
  - port: 443
    name: https
    protocol: TCP
