---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: internal-ipmi
  labels:
    kubernetes.io/service-name: internal-ipmi
addressType: IPv4
endpoints:
  - addresses:
      - 192.168.0.45
ports:
  - port: 443
    name: https
    protocol: TCP
