---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: external-service-httproute-ipmi
spec:
  parentRefs:
    - name: envoy-internal
      namespace: network

  hostnames:
    - ipmi.${SECRET_DOMAIN}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: ipmi-backend
          group: gateway.envoyproxy.io
          kind: Backend
          port: 443
