---
apiVersion: v1
kind: Service
metadata:
  name: internal-ipmi
spec:
  selector:
    app: ipmi-proxy
  ports:
    - port: 80
      targetPort: 80
      name: https
    - port: 8080
      targetPort: 8080
      name: http-health
