---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: external-service-tlsroute-ipmi
  annotations:
    external-dns.alpha.kubernetes.io/target: "internal-tls.${SECRET_DOMAIN}"
spec:
  parentRefs:
    - name: envoy-internal-tls
      namespace: network
      sectionName: tls
  hostnames:
    - ipmi.${SECRET_DOMAIN}
  rules:
    - backendRefs:
        - name: internal-ipmi
          port: 443

