apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:JT3Nz7c7Fw6nOVHl7L3CZIToq9aVkybGQ7DqkPFN1qO+q7oEWMzQyg==,iv:q4pMngp4u8AZwFzGK7ndch8J/I8e0C4kSWaPwaTU6zo=,tag:4nlN1v+vT3S+274p6/yrvQ==,type:str]
sops:
  age:
    - recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCNzlWME5uM1Nvb1dEZmw4
        QSs2dXVtaDNHT3Q4ZXpEVUZ6WnowckMvdlFBCjdvY3VQSXVCWlRpZUNBcDFZMFpP
        amtpUnNiODBRbUVNMmlMV2Y0UExHSDQKLS0tIEUyM3d1NS81QVhGSzBYMGdaZW1J
        TEFvNzNoM2FrM1oyK01weVI4TTh5TlkKwDWjquz0BTITHKZLnHOuRe8lETv2/Uaj
        zootSJLVQs/L0nEv/0QAMx6B+L651dzEmJC6/6ymNcATWMIWC0h1Vg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-02T19:38:50Z"
  mac: ENC[AES256_GCM,data:nsuZHl/oZwoXWwC/3WjhLmzYak92Q4EQQzmabC1b3r7o6Pws2/tcn4g7N5qT2F890Y5KZRLk8pwcXLIblRCJJ9D19MXluwqRG8nqqUoz/0Na+xnkCIj2SHanZ1sUuMwPeAPDE0EFRkZ+dheIb6XBQUt7uzOfTx6qeT00BBUKkDQ=,iv:bLFuVNSp806lqfZAUo8x8Eupj5LRuuGRnAQxdGzoDtU=,tag:2g1QaFZjvOjlvC/btwVk/g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
