---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cert-manager.io/issuer_v1.json
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: volsync-metrics
  namespace: volsync-system
spec:
  selfSigned: {}
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: volsync-metrics-tls
  namespace: volsync-system
spec:
  commonName: volsync-metrics
  dnsNames:
    - volsync-metrics
    - volsync-metrics.volsync-system
    - volsync-metrics.volsync-system.svc
    - volsync-metrics.volsync-system.svc.cluster.local
  duration: 2160h
  isCA: false
  issuerRef:
    name: volsync-metrics
    kind: Issuer
  renewBefore: 360h
  secretName: volsync-metrics-tls
  usages:
    - server auth
    - client auth
