---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: volsync
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: volsync

  values:
    manageCRDs: true
    replicaCount: 1
    metrics:
      disableAuth: false
      kubeRbacProxy:
        extraArgs:
          - --tls-cert-file=/etc/tls/tls.crt
          - --tls-private-key-file=/etc/tls/tls.key
        extraVolumeMounts:
          - name: tls
            mountPath: /etc/tls
            readOnly: true
        extraVolumes:
          - name: tls
            secret:
              secretName: volsync-metrics-tls
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
