apiVersion: v1
kind: Secret
metadata:
    name: opencode-secret
    namespace: ai
stringData:
    OLLAMA_API_KEY: ENC[AES256_GCM,data:5bo0guYPLz4wa4ep6GLrmexR5cmtBp0ZYD4jjrUVutafZS0=,iv:bK0OETS+pzA6f+SbCZOux03EeJq2F2jnXr8TdgjRap0=,tag:ppgqDoaq8agrRJt6bUcMxg==,type:str]
    OPENCODE_MCP_URL: ENC[AES256_GCM,data:nCEZtSI4dZKYrsr3kcP4U2SyqH8g+2CHGSUIA0Fi,iv:thgOTWZOYCO5OviYSZjvhO9RoIkwIGe9KPy3o1/cE/s=,tag:fq4WTwdHmKjPy0hzyeGWFQ==,type:str]
sops:
    age:
        - recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzN1hlUXk3aVE3WG1HOGdx
            cVVuWTVDUVZqYjFyRG1HemQ4S0UvUkVWL1VzCkVTb1ZXeWdrRjd2Znd3UU44ZG5a
            ek5ZRzRFNHB4djhsdnFQNHh1VG5nOHMKLS0tIDF4Wm5WNHZUMlltWGRVeDZ3cnNU
            WG95OGltTkZuUXVtWXMyVXZiWHNRNDgKfQluc8+RUhcF9f3h7ukyMeFVwWGI5Ur2
            SX8VZ+hwI1dgLKuFdE2TVSMzBe25xaVAwyqZjLq7nq1UskT3ywVpKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T21:30:36Z"
    mac: ENC[AES256_GCM,data:OGt+q0DXOSEtD6JEuNsNVL9rfdzzKVjMYd0dLTPbKyUHEui3I7Z5JGqn2kalgqRkbWxqQ/EDAhj4kt6KK0J4IRT+Lx6aJ+lIhelQgXZy4knGK+DscLR+9qXeHObuIEJ2j01GouboGfiDTi28JNbBPzFOGyqfA8HdQzEaLXrbQ8A=,iv:syTtKeMGezYfxO14/cXtj7Q+uo5tlQ23ffcy6T6LOiI=,tag:vKDO2h2AoJWtS5DdkN9Gyw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.1
