apiVersion: v1
kind: Secret
metadata:
    name: opencode-secret
    namespace: ai
stringData:
    OLLAMA_API_KEY: ENC[AES256_GCM,data:5bo0guYPLz4wa4ep6GLrmexR5cmtBp0ZYD4jjrUVutafZS0=,iv:bK0OETS+pzA6f+SbCZOux03EeJq2F2jnXr8TdgjRap0=,tag:ppgqDoaq8agrRJt6bUcMxg==,type:str]
sops:
    age:
        - recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzN1hlUXk3aVE3WG1HOGdx
            cVVuWTVDUVZqYjFyRG1HemQ4S0UvUkVWL1VzCkVTb1ZXeWdrRjd2Znd3UU44ZG5a
            ek5ZRzRFNHB4djhsdnFQNHh1VG5nOHMKLS0tIDF4Wm5WNHZUMlltWGRVeDZ3cnNU
            WG95OGltTkZuUXVtWXMyVXZiWHNRNDgKfQluc8+RUhcF9f3h7ukyMeFVwWGI5Ur2
            SX8VZ+hwI1dgLKuFdE2TVSMzBe25xaVAwyqZjLq7nq1UskT3ywVpKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T14:49:01Z"
    mac: ENC[AES256_GCM,data:GS0fJE9kSMqP24P4IeUUvNcDo7eLuiOyM6+0v6ucw53/Zw1HqLlCIkHiNc7WQ/8eQJPJT8UYEamF/Pvmt8LI8pkWGjTgyfM3F08w3rK5uwhaTqA+vNcFuqf+kR7cTDLi2NptmxxuSImn3TYk6p39FrQsf1yWSPy4gPZkR2Ofo+I=,iv:6y88V6mvV3LNhCv5bNMyRSSuPTZjmXlRtb43OEKgOIU=,tag:ryTQr5FjeShJaTUxj6D+gQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.1
