---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
  - lvm-snapshotclass.yaml
  - lvm-storageclass.yaml
  - ocirepository.yaml
  - zfs-snapshotclass.yaml
  - zfs-storageclass.yaml
