---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - diskpool.yaml
  - helmrelease.yaml
  - mayastor-snapshotclass.yaml
  - mayastor-storageclass.yaml
  - ocirepository.yaml
  - zfs-snapshotclass.yaml
  - zfs-storageclass.yaml
