---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-lvm
provisioner: local.csi.openebs.io
parameters:
  storage: lvm
  volgroup: lvmvg
reclaimPolicy: Delete
allowVolumeExpansion: true
