---
# 3-replica: High availability, data replicated across all nodes
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mayastor
provisioner: io.openebs.csi-mayastor
parameters:
  protocol: nvmf
  repl: "3"
reclaimPolicy: Delete
allowVolumeExpansion: true
